23:28:02.757 [LlapScheduler] ERROR org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService - Fatal error: scheduler thread has failed and will now exit
java.lang.RuntimeException: java.lang.InterruptedException
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2331) ~[test-classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2564) [classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2531) [classes/:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:108) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:41) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77) [guava-19.0.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_292]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_292]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
Caused by: java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014) ~[?:1.8.0_292]
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048) ~[?:1.8.0_292]
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2329) ~[test-classes/:?]
	... 8 more
23:28:02.781 [LlapScheduler] ERROR org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService - Fatal error: scheduler thread has failed and will now exit
java.lang.RuntimeException: java.lang.InterruptedException
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2331) ~[test-classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2564) [classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2531) [classes/:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:108) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:41) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77) [guava-19.0.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_292]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_292]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
Caused by: java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014) ~[?:1.8.0_292]
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048) ~[?:1.8.0_292]
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2329) ~[test-classes/:?]
	... 8 more
23:28:02.808 [LlapScheduler] ERROR org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService - Fatal error: scheduler thread has failed and will now exit
java.lang.RuntimeException: java.lang.InterruptedException
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2331) ~[test-classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2564) [classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2531) [classes/:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:108) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:41) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77) [guava-19.0.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_292]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_292]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
Caused by: java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014) ~[?:1.8.0_292]
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048) ~[?:1.8.0_292]
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2329) ~[test-classes/:?]
	... 8 more
23:28:02.830 [LlapScheduler] ERROR org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService - Fatal error: scheduler thread has failed and will now exit
java.lang.RuntimeException: java.lang.InterruptedException
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2331) ~[test-classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2564) [classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2531) [classes/:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:108) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:41) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77) [guava-19.0.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_292]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_292]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
Caused by: java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014) ~[?:1.8.0_292]
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048) ~[?:1.8.0_292]
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2329) ~[test-classes/:?]
	... 8 more
23:28:02.866 [LlapScheduler] ERROR org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService - Fatal error: scheduler thread has failed and will now exit
java.lang.RuntimeException: java.lang.InterruptedException
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2331) ~[test-classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2564) [classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2531) [classes/:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:108) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:41) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77) [guava-19.0.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_292]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_292]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
Caused by: java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014) ~[?:1.8.0_292]
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048) ~[?:1.8.0_292]
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2329) ~[test-classes/:?]
	... 8 more
23:28:02.885 [LlapScheduler] ERROR org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService - Fatal error: scheduler thread has failed and will now exit
java.lang.RuntimeException: java.lang.InterruptedException
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2331) ~[test-classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2564) [classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2531) [classes/:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:108) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:41) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77) [guava-19.0.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_292]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_292]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
Caused by: java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014) ~[?:1.8.0_292]
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048) ~[?:1.8.0_292]
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2329) ~[test-classes/:?]
	... 8 more
23:28:02.910 [LlapScheduler] ERROR org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService - Fatal error: scheduler thread has failed and will now exit
java.lang.RuntimeException: java.lang.InterruptedException
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2331) ~[test-classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2564) [classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2531) [classes/:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:108) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:41) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77) [guava-19.0.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_292]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_292]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
Caused by: java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014) ~[?:1.8.0_292]
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048) ~[?:1.8.0_292]
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2329) ~[test-classes/:?]
	... 8 more
23:28:02.928 [LlapScheduler] ERROR org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService - Fatal error: scheduler thread has failed and will now exit
java.lang.RuntimeException: java.lang.InterruptedException
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2331) ~[test-classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2564) [classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2531) [classes/:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:108) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:41) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77) [guava-19.0.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_292]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_292]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
Caused by: java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014) ~[?:1.8.0_292]
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048) ~[?:1.8.0_292]
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2329) ~[test-classes/:?]
	... 8 more
23:28:02.943 [LlapScheduler] ERROR org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService - Fatal error: scheduler thread has failed and will now exit
java.lang.RuntimeException: java.lang.InterruptedException
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2331) ~[test-classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2564) [classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2531) [classes/:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:108) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:41) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77) [guava-19.0.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_292]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_292]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
Caused by: java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014) ~[?:1.8.0_292]
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048) ~[?:1.8.0_292]
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2329) ~[test-classes/:?]
	... 8 more
23:28:02.990 [LlapScheduler] ERROR org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService - Fatal error: scheduler thread has failed and will now exit
java.lang.RuntimeException: java.lang.InterruptedException
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2331) ~[test-classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2564) [classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2531) [classes/:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:108) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:41) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77) [guava-19.0.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_292]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_292]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
Caused by: java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014) ~[?:1.8.0_292]
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048) ~[?:1.8.0_292]
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2329) ~[test-classes/:?]
	... 8 more
23:28:03.005 [LlapScheduler] ERROR org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService - Fatal error: scheduler thread has failed and will now exit
java.lang.RuntimeException: java.lang.InterruptedException
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2331) ~[test-classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2564) [classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2531) [classes/:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:108) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:41) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77) [guava-19.0.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_292]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_292]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
Caused by: java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014) ~[?:1.8.0_292]
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048) ~[?:1.8.0_292]
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2329) ~[test-classes/:?]
	... 8 more
23:28:03.020 [LlapScheduler] ERROR org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService - Fatal error: scheduler thread has failed and will now exit
java.lang.RuntimeException: java.lang.InterruptedException
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2331) ~[test-classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2564) [classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2531) [classes/:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:108) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:41) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77) [guava-19.0.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_292]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_292]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
Caused by: java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014) ~[?:1.8.0_292]
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048) ~[?:1.8.0_292]
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2329) ~[test-classes/:?]
	... 8 more
23:28:03.034 [LlapScheduler] ERROR org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService - Fatal error: scheduler thread has failed and will now exit
java.lang.RuntimeException: java.lang.InterruptedException
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2331) ~[test-classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2564) [classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2531) [classes/:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:108) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:41) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77) [guava-19.0.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_292]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_292]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
Caused by: java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014) ~[?:1.8.0_292]
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048) ~[?:1.8.0_292]
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2329) ~[test-classes/:?]
	... 8 more
23:28:03.063 [LlapScheduler] ERROR org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService - Fatal error: scheduler thread has failed and will now exit
java.lang.RuntimeException: java.lang.InterruptedException
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2331) ~[test-classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2564) [classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2531) [classes/:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:108) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:41) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77) [guava-19.0.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_292]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_292]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
Caused by: java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014) ~[?:1.8.0_292]
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048) ~[?:1.8.0_292]
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2329) ~[test-classes/:?]
	... 8 more
23:28:03.078 [LlapScheduler] ERROR org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService - Fatal error: scheduler thread has failed and will now exit
java.lang.RuntimeException: java.lang.InterruptedException
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2331) ~[test-classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2564) [classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2531) [classes/:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:108) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:41) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77) [guava-19.0.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_292]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_292]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
Caused by: java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014) ~[?:1.8.0_292]
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048) ~[?:1.8.0_292]
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2329) ~[test-classes/:?]
	... 8 more
23:28:03.096 [LlapScheduler] ERROR org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService - Fatal error: scheduler thread has failed and will now exit
java.lang.RuntimeException: java.lang.InterruptedException
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2331) ~[test-classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2564) [classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2531) [classes/:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:108) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:41) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77) [guava-19.0.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_292]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_292]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
Caused by: java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014) ~[?:1.8.0_292]
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048) ~[?:1.8.0_292]
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2329) ~[test-classes/:?]
	... 8 more
23:28:03.128 [LlapScheduler] ERROR org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService - Fatal error: scheduler thread has failed and will now exit
java.lang.RuntimeException: java.lang.InterruptedException
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2331) ~[test-classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2564) [classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2531) [classes/:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:108) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:41) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77) [guava-19.0.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_292]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_292]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
Caused by: java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014) ~[?:1.8.0_292]
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048) ~[?:1.8.0_292]
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2329) ~[test-classes/:?]
	... 8 more
23:28:03.141 [LlapScheduler] ERROR org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService - Fatal error: scheduler thread has failed and will now exit
java.lang.RuntimeException: java.lang.InterruptedException
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2331) ~[test-classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2564) [classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2531) [classes/:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:108) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:41) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77) [guava-19.0.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_292]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_292]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
Caused by: java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014) ~[?:1.8.0_292]
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048) ~[?:1.8.0_292]
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2329) ~[test-classes/:?]
	... 8 more
23:28:03.174 [LlapScheduler] ERROR org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService - Fatal error: scheduler thread has failed and will now exit
java.lang.RuntimeException: java.lang.InterruptedException
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2331) ~[test-classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2564) [classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2531) [classes/:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:108) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:41) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77) [guava-19.0.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_292]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_292]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
Caused by: java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014) ~[?:1.8.0_292]
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048) ~[?:1.8.0_292]
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2329) ~[test-classes/:?]
	... 8 more
23:28:03.194 [LlapScheduler] ERROR org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService - Fatal error: scheduler thread has failed and will now exit
java.lang.RuntimeException: java.lang.InterruptedException
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2331) ~[test-classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2564) [classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2531) [classes/:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:108) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:41) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77) [guava-19.0.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_292]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_292]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
Caused by: java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014) ~[?:1.8.0_292]
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048) ~[?:1.8.0_292]
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2329) ~[test-classes/:?]
	... 8 more
23:28:03.212 [LlapScheduler] ERROR org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService - Fatal error: scheduler thread has failed and will now exit
java.lang.RuntimeException: java.lang.InterruptedException
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2331) ~[test-classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2564) [classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2531) [classes/:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:108) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:41) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77) [guava-19.0.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_292]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_292]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
Caused by: java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014) ~[?:1.8.0_292]
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048) ~[?:1.8.0_292]
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2329) ~[test-classes/:?]
	... 8 more
23:28:03.225 [LlapScheduler] ERROR org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService - Fatal error: scheduler thread has failed and will now exit
java.lang.RuntimeException: java.lang.InterruptedException
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2331) ~[test-classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2564) [classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2531) [classes/:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:108) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:41) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77) [guava-19.0.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_292]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_292]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
Caused by: java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014) ~[?:1.8.0_292]
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048) ~[?:1.8.0_292]
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2329) ~[test-classes/:?]
	... 8 more
23:28:03.238 [LlapScheduler] ERROR org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService - Fatal error: scheduler thread has failed and will now exit
java.lang.RuntimeException: java.lang.InterruptedException
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2331) ~[test-classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2564) [classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2531) [classes/:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:108) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:41) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77) [guava-19.0.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_292]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_292]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
Caused by: java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014) ~[?:1.8.0_292]
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048) ~[?:1.8.0_292]
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2329) ~[test-classes/:?]
	... 8 more
23:28:03.251 [LlapScheduler] ERROR org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService - Fatal error: scheduler thread has failed and will now exit
java.lang.RuntimeException: java.lang.InterruptedException
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2331) ~[test-classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2564) [classes/:?]
	at org.apache.hadoop.hive.llap.tezplugins.LlapTaskSchedulerService$SchedulerCallable.call(LlapTaskSchedulerService.java:2531) [classes/:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:108) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:41) [guava-19.0.jar:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77) [guava-19.0.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_292]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_292]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_292]
Caused by: java.lang.InterruptedException
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014) ~[?:1.8.0_292]
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048) ~[?:1.8.0_292]
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskSchedulerService$LlapTaskSchedulerServiceForTest.schedulePendingTasks(TestLlapTaskSchedulerService.java:2329) ~[test-classes/:?]
	... 8 more
23:28:07.546 [Thread-2] ERROR org.apache.hadoop.hive.llap.tezplugins.LlapTaskCommunicator - Failed to send state update to node: host1:15002, Killing all attempts running on node. Attempted StateUpdate=query_identifier {
  application_id_string: "application_1000_0001"
  dag_index: 200
  app_attempt_number: 100
}
src_name: "vertexName1"
state: S_SUCCEEDED

java.io.IOException: Force failing host1
	at org.apache.hadoop.hive.llap.tezplugins.TestLlapTaskCommunicator$FinishableStatusUpdateTestAnswer$1.run(TestLlapTaskCommunicator.java:224) [test-classes/:?]
