<?xml version="1.0" encoding="UTF-8"?>
<testsuite xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://maven.apache.org/surefire/maven-surefire-plugin/xsd/surefire-test-report-3.0.xsd" version="3.0" name="org.apache.nifi.processors.standard.TestPutSQL" time="1.146" tests="41" errors="0" skipped="0" failures="0">
  <properties>
    <property name="sun.desktop" value="gnome"/>
    <property name="awt.toolkit" value="sun.awt.X11.XToolkit"/>
    <property name="file.encoding.pkg" value="sun.io"/>
    <property name="java.specification.version" value="1.8"/>
    <property name="sun.cpu.isalist" value=""/>
    <property name="sun.jnu.encoding" value="UTF-8"/>
    <property name="java.class.path" value="/home/alex/Repositories/nifi/nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/target/test-classes:/home/alex/Repositories/nifi/nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/target/classes:/home/alex/.m2/repository/org/apache/ftpserver/ftpserver-core/1.1.1/ftpserver-core-1.1.1.jar:/home/alex/.m2/repository/org/apache/ftpserver/ftplet-api/1.1.1/ftplet-api-1.1.1.jar:/home/alex/.m2/repository/org/slf4j/slf4j-api/1.7.32/slf4j-api-1.7.32.jar:/home/alex/.m2/repository/org/apache/mina/mina-core/2.0.16/mina-core-2.0.16.jar:/home/alex/Repositories/nifi/nifi-api/target/classes:/home/alex/Repositories/nifi/nifi-commons/nifi-expression-language/target/classes:/home/alex/.m2/repository/org/antlr/antlr-runtime/3.5.2/antlr-runtime-3.5.2.jar:/home/alex/Repositories/nifi/nifi-commons/nifi-parameter/target/classes:/home/alex/Repositories/nifi/nifi-commons/nifi-uuid5/target/classes:/home/alex/.m2/repository/org/apache/commons/commons-text/1.8/commons-text-1.8.jar:/home/alex/Repositories/nifi/nifi-nar-bundles/nifi-extension-utils/nifi-processor-utils/target/classes:/home/alex/Repositories/nifi/nifi-commons/nifi-security-socket-ssl/target/classes:/home/alex/Repositories/nifi/nifi-nar-bundles/nifi-extension-utils/nifi-event-transport/target/classes:/home/alex/.m2/repository/io/netty/netty-handler/4.1.69.Final/netty-handler-4.1.69.Final.jar:/home/alex/.m2/repository/io/netty/netty-common/4.1.69.Final/netty-common-4.1.69.Final.jar:/home/alex/.m2/repository/io/netty/netty-resolver/4.1.69.Final/netty-resolver-4.1.69.Final.jar:/home/alex/.m2/repository/io/netty/netty-transport/4.1.69.Final/netty-transport-4.1.69.Final.jar:/home/alex/.m2/repository/io/netty/netty-codec/4.1.69.Final/netty-codec-4.1.69.Final.jar:/home/alex/Repositories/nifi/nifi-nar-bundles/nifi-extension-utils/nifi-syslog-utils/target/classes:/home/alex/.m2/repository/com/github/palindromicity/simple-syslog-5424/0.0.16/simple-syslog-5424-0.0.16.jar:/home/alex/.m2/repository/org/antlr/antlr4-runtime/4.7.2/antlr4-runtime-4.7.2.jar:/home/alex/Repositories/nifi/nifi-commons/nifi-utils/target/classes:/home/alex/Repositories/nifi/nifi-commons/nifi-record-path/target/classes:/home/alex/Repositories/nifi/nifi-commons/nifi-properties/target/classes:/home/alex/Repositories/nifi/nifi-commons/nifi-property-utils/target/classes:/home/alex/.m2/repository/com/github/ben-manes/caffeine/caffeine/2.8.1/caffeine-2.8.1.jar:/home/alex/Repositories/nifi/nifi-nar-bundles/nifi-standard-services/nifi-ssl-context-service-api/target/classes:/home/alex/Repositories/nifi/nifi-commons/nifi-security-utils-api/target/classes:/home/alex/Repositories/nifi/nifi-nar-bundles/nifi-standard-services/nifi-lookup-service-api/target/classes:/home/alex/Repositories/nifi/nifi-commons/nifi-flowfile-packager/target/classes:/home/alex/Repositories/nifi/nifi-nar-bundles/nifi-standard-services/nifi-distributed-cache-client-service-api/target/classes:/home/alex/Repositories/nifi/nifi-nar-bundles/nifi-standard-services/nifi-http-context-map-api/target/classes:/home/alex/Repositories/nifi/nifi-nar-bundles/nifi-standard-services/nifi-record-serialization-service-api/target/classes:/home/alex/Repositories/nifi/nifi-nar-bundles/nifi-standard-services/nifi-proxy-configuration-api/target/classes:/home/alex/Repositories/nifi/nifi-commons/nifi-record/target/classes:/home/alex/Repositories/nifi/nifi-nar-bundles/nifi-standard-services/nifi-record-sink-api/target/classes:/home/alex/.m2/repository/commons-io/commons-io/2.10.0/commons-io-2.10.0.jar:/home/alex/.m2/repository/javax/ws/rs/javax.ws.rs-api/2.1/javax.ws.rs-api-2.1.jar:/home/alex/.m2/repository/commons-net/commons-net/3.6/commons-net-3.6.jar:/home/alex/.m2/repository/org/apache/commons/commons-compress/1.21/commons-compress-1.21.jar:/home/alex/.m2/repository/org/apache/commons/commons-lang3/3.9/commons-lang3-3.9.jar:/home/alex/.m2/repository/org/bouncycastle/bcprov-jdk15on/1.69/bcprov-jdk15on-1.69.jar:/home/alex/.m2/repository/org/bouncycastle/bcpg-jdk15on/1.69/bcpg-jdk15on-1.69.jar:/home/alex/.m2/repository/org/bouncycastle/bcpkix-jdk15on/1.69/bcpkix-jdk15on-1.69.jar:/home/alex/.m2/repository/org/bouncycastle/bcutil-jdk15on/1.69/bcutil-jdk15on-1.69.jar:/home/alex/.m2/repository/commons-codec/commons-codec/1.14/commons-codec-1.14.jar:/home/alex/Repositories/nifi/nifi-commons/nifi-security-utils/target/classes:/home/alex/Repositories/nifi/nifi-commons/nifi-security-kms/target/classes:/home/alex/.m2/repository/org/apache/commons/commons-configuration2/2.7/commons-configuration2-2.7.jar:/home/alex/.m2/repository/com/hierynomus/sshj/0.32.0/sshj-0.32.0.jar:/home/alex/.m2/repository/com/jcraft/jzlib/1.1.3/jzlib-1.1.3.jar:/home/alex/.m2/repository/com/hierynomus/asn-one/0.6.0/asn-one-0.6.0.jar:/home/alex/.m2/repository/net/i2p/crypto/eddsa/0.3.0/eddsa-0.3.0.jar:/home/alex/.m2/repository/org/eclipse/jetty/jetty-server/9.4.44.v20210927/jetty-server-9.4.44.v20210927.jar:/home/alex/.m2/repository/javax/servlet/javax.servlet-api/3.1.0/javax.servlet-api-3.1.0.jar:/home/alex/.m2/repository/org/eclipse/jetty/jetty-http/9.4.44.v20210927/jetty-http-9.4.44.v20210927.jar:/home/alex/.m2/repository/org/eclipse/jetty/jetty-util/9.4.44.v20210927/jetty-util-9.4.44.v20210927.jar:/home/alex/.m2/repository/org/eclipse/jetty/jetty-io/9.4.44.v20210927/jetty-io-9.4.44.v20210927.jar:/home/alex/.m2/repository/org/eclipse/jetty/jetty-servlet/9.4.44.v20210927/jetty-servlet-9.4.44.v20210927.jar:/home/alex/.m2/repository/org/eclipse/jetty/jetty-security/9.4.44.v20210927/jetty-security-9.4.44.v20210927.jar:/home/alex/.m2/repository/org/eclipse/jetty/jetty-util-ajax/9.4.44.v20210927/jetty-util-ajax-9.4.44.v20210927.jar:/home/alex/.m2/repository/org/apache/httpcomponents/httpclient/4.5.5/httpclient-4.5.5.jar:/home/alex/.m2/repository/commons-logging/commons-logging/1.2/commons-logging-1.2.jar:/home/alex/.m2/repository/org/apache/httpcomponents/httpcore/4.4.9/httpcore-4.4.9.jar:/home/alex/.m2/repository/jakarta/activation/jakarta.activation-api/2.0.1/jakarta.activation-api-2.0.1.jar:/home/alex/.m2/repository/com/sun/activation/jakarta.activation/2.0.1/jakarta.activation-2.0.1.jar:/home/alex/.m2/repository/jakarta/mail/jakarta.mail-api/2.0.1/jakarta.mail-api-2.0.1.jar:/home/alex/.m2/repository/com/sun/mail/jakarta.mail/2.0.1/jakarta.mail-2.0.1.jar:/home/alex/.m2/repository/com/github/jponge/lzma-java/1.3/lzma-java-1.3.jar:/home/alex/.m2/repository/org/tukaani/xz/1.8/xz-1.8.jar:/home/alex/.m2/repository/net/sf/saxon/Saxon-HE/10.6/Saxon-HE-10.6.jar:/home/alex/Repositories/nifi/nifi-commons/nifi-socket-utils/target/classes:/home/alex/Repositories/nifi/nifi-commons/nifi-logging-utils/target/classes:/home/alex/Repositories/nifi/nifi-nar-bundles/nifi-standard-services/nifi-load-distribution-service-api/target/classes:/home/alex/.m2/repository/javax/jms/javax.jms-api/2.0.1/javax.jms-api-2.0.1.jar:/home/alex/.m2/repository/org/apache/activemq/activemq-client/5.15.15/activemq-client-5.15.15.jar:/home/alex/.m2/repository/org/apache/geronimo/specs/geronimo-jms_1.1_spec/1.1.1/geronimo-jms_1.1_spec-1.1.1.jar:/home/alex/.m2/repository/org/fusesource/hawtbuf/hawtbuf/1.11/hawtbuf-1.11.jar:/home/alex/.m2/repository/org/apache/geronimo/specs/geronimo-j2ee-management_1.1_spec/1.0.1/geronimo-j2ee-management_1.1_spec-1.0.1.jar:/home/alex/.m2/repository/com/jayway/jsonpath/json-path/2.6.0/json-path-2.6.0.jar:/home/alex/.m2/repository/net/minidev/json-smart/2.4.7/json-smart-2.4.7.jar:/home/alex/.m2/repository/net/minidev/accessors-smart/2.4.7/accessors-smart-2.4.7.jar:/home/alex/.m2/repository/org/ow2/asm/asm/9.1/asm-9.1.jar:/home/alex/.m2/repository/org/apache/tika/tika-core/1.26/tika-core-1.26.jar:/home/alex/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.12.3/jackson-databind-2.12.3.jar:/home/alex/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.12.3/jackson-annotations-2.12.3.jar:/home/alex/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.12.3/jackson-core-2.12.3.jar:/home/alex/Repositories/nifi/nifi-nar-bundles/nifi-extension-utils/nifi-record-utils/nifi-avro-record-utils/target/classes:/home/alex/Repositories/nifi/nifi-nar-bundles/nifi-extension-utils/nifi-record-utils/nifi-standard-record-utils/target/classes:/home/alex/.m2/repository/org/apache/avro/avro/1.8.1/avro-1.8.1.jar:/home/alex/.m2/repository/org/codehaus/jackson/jackson-core-asl/1.9.13/jackson-core-asl-1.9.13.jar:/home/alex/.m2/repository/org/codehaus/jackson/jackson-mapper-asl/1.9.13/jackson-mapper-asl-1.9.13.jar:/home/alex/.m2/repository/com/thoughtworks/paranamer/paranamer/2.7/paranamer-2.7.jar:/home/alex/Repositories/nifi/nifi-nar-bundles/nifi-standard-services/nifi-dbcp-service-api/target/classes:/home/alex/.m2/repository/com/squareup/okhttp3/okhttp/4.9.2/okhttp-4.9.2.jar:/home/alex/.m2/repository/com/squareup/okio/okio/2.8.0/okio-2.8.0.jar:/home/alex/.m2/repository/org/jetbrains/kotlin/kotlin-stdlib-common/1.4.0/kotlin-stdlib-common-1.4.0.jar:/home/alex/.m2/repository/org/jetbrains/kotlin/kotlin-stdlib/1.4.10/kotlin-stdlib-1.4.10.jar:/home/alex/.m2/repository/org/jetbrains/annotations/13.0/annotations-13.0.jar:/home/alex/.m2/repository/io/github/rburgst/okhttp-digest/2.5/okhttp-digest-2.5.jar:/home/alex/.m2/repository/at/favre/lib/bcrypt/0.9.0/bcrypt-0.9.0.jar:/home/alex/.m2/repository/at/favre/lib/bytes/1.3.0/bytes-1.3.0.jar:/home/alex/.m2/repository/com/google/guava/guava/28.0-jre/guava-28.0-jre.jar:/home/alex/.m2/repository/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar:/home/alex/.m2/repository/com/google/guava/listenablefuture/9999.0-empty-to-avoid-conflict-with-guava/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar:/home/alex/.m2/repository/com/google/code/findbugs/jsr305/3.0.2/jsr305-3.0.2.jar:/home/alex/.m2/repository/org/checkerframework/checker-qual/2.8.1/checker-qual-2.8.1.jar:/home/alex/.m2/repository/com/google/errorprone/error_prone_annotations/2.3.2/error_prone_annotations-2.3.2.jar:/home/alex/.m2/repository/com/google/j2objc/j2objc-annotations/1.3/j2objc-annotations-1.3.jar:/home/alex/.m2/repository/org/codehaus/mojo/animal-sniffer-annotations/1.17/animal-sniffer-annotations-1.17.jar:/home/alex/Repositories/nifi/nifi-mock/target/classes:/home/alex/Repositories/nifi/nifi-framework-api/target/classes:/home/alex/Repositories/nifi/nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-core-api/target/classes:/home/alex/Repositories/nifi/nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-nar-utils/target/classes:/home/alex/Repositories/nifi/nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-client-dto/target/classes:/home/alex/.m2/repository/io/swagger/swagger-annotations/1.6.0/swagger-annotations-1.6.0.jar:/home/alex/Repositories/nifi/nifi-commons/nifi-site-to-site-client/target/classes:/home/alex/.m2/repository/org/apache/httpcomponents/httpasyncclient/4.1.4/httpasyncclient-4.1.4.jar:/home/alex/.m2/repository/org/apache/httpcomponents/httpcore-nio/4.4.10/httpcore-nio-4.4.10.jar:/home/alex/Repositories/nifi/nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-authorization/target/classes:/home/alex/Repositories/nifi/nifi-registry/nifi-registry-core/nifi-registry-data-model/target/classes:/home/alex/Repositories/nifi/nifi-registry/nifi-registry-core/nifi-registry-revision/nifi-registry-revision-entity-model/target/classes:/home/alex/Repositories/nifi/nifi-registry/nifi-registry-core/nifi-registry-client/target/classes:/home/alex/Repositories/nifi/nifi-registry/nifi-registry-core/nifi-registry-security-utils/target/classes:/home/alex/.m2/repository/org/glassfish/jersey/core/jersey-client/2.33/jersey-client-2.33.jar:/home/alex/.m2/repository/jakarta/ws/rs/jakarta.ws.rs-api/2.1.6/jakarta.ws.rs-api-2.1.6.jar:/home/alex/.m2/repository/org/glassfish/hk2/external/jakarta.inject/2.6.1/jakarta.inject-2.6.1.jar:/home/alex/.m2/repository/org/glassfish/jersey/media/jersey-media-json-jackson/2.33/jersey-media-json-jackson-2.33.jar:/home/alex/.m2/repository/org/glassfish/jersey/ext/jersey-entity-filtering/2.33/jersey-entity-filtering-2.33.jar:/home/alex/.m2/repository/org/glassfish/jersey/inject/jersey-hk2/2.33/jersey-hk2-2.33.jar:/home/alex/.m2/repository/org/glassfish/hk2/hk2-locator/2.6.1/hk2-locator-2.6.1.jar:/home/alex/.m2/repository/org/glassfish/hk2/external/aopalliance-repackaged/2.6.1/aopalliance-repackaged-2.6.1.jar:/home/alex/.m2/repository/org/glassfish/hk2/hk2-api/2.6.1/hk2-api-2.6.1.jar:/home/alex/.m2/repository/org/glassfish/hk2/hk2-utils/2.6.1/hk2-utils-2.6.1.jar:/home/alex/.m2/repository/org/javassist/javassist/3.25.0-GA/javassist-3.25.0-GA.jar:/home/alex/.m2/repository/org/glassfish/jersey/core/jersey-common/2.33/jersey-common-2.33.jar:/home/alex/.m2/repository/jakarta/annotation/jakarta.annotation-api/1.3.5/jakarta.annotation-api-1.3.5.jar:/home/alex/.m2/repository/org/glassfish/hk2/osgi-resource-locator/1.0.3/osgi-resource-locator-1.0.3.jar:/home/alex/.m2/repository/org/glassfish/jersey/media/jersey-media-multipart/2.33/jersey-media-multipart-2.33.jar:/home/alex/.m2/repository/org/jvnet/mimepull/mimepull/1.9.13/mimepull-1.9.13.jar:/home/alex/Repositories/nifi/nifi-commons/nifi-data-provenance-utils/target/classes:/home/alex/Repositories/nifi/nifi-nar-bundles/nifi-standard-services/nifi-distributed-cache-services-bundle/nifi-distributed-cache-client-service/target/classes:/home/alex/Repositories/nifi/nifi-nar-bundles/nifi-standard-services/nifi-distributed-cache-services-bundle/nifi-distributed-cache-protocol/target/classes:/home/alex/.m2/repository/io/netty/netty-buffer/4.1.69.Final/netty-buffer-4.1.69.Final.jar:/home/alex/.m2/repository/com/google/http-client/google-http-client/1.28.0/google-http-client-1.28.0.jar:/home/alex/.m2/repository/io/opencensus/opencensus-api/0.18.0/opencensus-api-0.18.0.jar:/home/alex/.m2/repository/io/grpc/grpc-context/1.14.0/grpc-context-1.14.0.jar:/home/alex/.m2/repository/io/opencensus/opencensus-contrib-http-util/0.18.0/opencensus-contrib-http-util-0.18.0.jar:/home/alex/.m2/repository/org/apache/activemq/activemq-broker/5.15.14/activemq-broker-5.15.14.jar:/home/alex/.m2/repository/org/apache/activemq/activemq-openwire-legacy/5.15.14/activemq-openwire-legacy-5.15.14.jar:/home/alex/Repositories/nifi/nifi-nar-bundles/nifi-standard-services/nifi-ssl-context-bundle/nifi-ssl-context-service/target/classes:/home/alex/Repositories/nifi/nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-standard-prioritizers/target/classes:/home/alex/Repositories/nifi/nifi-nar-bundles/nifi-extension-utils/nifi-record-utils/nifi-mock-record-utils/target/classes:/home/alex/Repositories/nifi/nifi-nar-bundles/nifi-standard-services/nifi-record-serialization-services-bundle/nifi-record-serialization-services/target/classes:/home/alex/.m2/repository/org/apache/commons/commons-csv/1.8/commons-csv-1.8.jar:/home/alex/.m2/repository/com/fasterxml/jackson/dataformat/jackson-dataformat-csv/2.12.3/jackson-dataformat-csv-2.12.3.jar:/home/alex/.m2/repository/net/java/dev/stax-utils/stax-utils/20070216/stax-utils-20070216.jar:/home/alex/Repositories/nifi/nifi-nar-bundles/nifi-standard-services/nifi-lookup-services-bundle/nifi-lookup-services/target/classes:/home/alex/.m2/repository/commons-beanutils/commons-beanutils/1.9.4/commons-beanutils-1.9.4.jar:/home/alex/.m2/repository/commons-collections/commons-collections/3.2.2/commons-collections-3.2.2.jar:/home/alex/.m2/repository/com/maxmind/geoip2/geoip2/2.12.0/geoip2-2.12.0.jar:/home/alex/.m2/repository/com/maxmind/db/maxmind-db/1.2.2/maxmind-db-1.2.2.jar:/home/alex/.m2/repository/org/apache/derby/derby/10.14.2.0/derby-10.14.2.0.jar:/home/alex/.m2/repository/org/xerial/snappy/snappy-java/1.1.7.3/snappy-java-1.1.7.3.jar:/home/alex/.m2/repository/net/lingala/zip4j/zip4j/2.8.0/zip4j-2.8.0.jar:/home/alex/.m2/repository/com/h2database/h2/1.4.187/h2-1.4.187.jar:/home/alex/.m2/repository/org/mockftpserver/MockFtpServer/2.7.1/MockFtpServer-2.7.1.jar:/home/alex/.m2/repository/org/apache/sshd/sshd-core/1.7.0/sshd-core-1.7.0.jar:/home/alex/.m2/repository/com/bazaarvoice/jolt/jolt-core/0.1.1/jolt-core-0.1.1.jar:/home/alex/.m2/repository/javax/inject/javax.inject/1/javax.inject-1.jar:/home/alex/.m2/repository/com/bazaarvoice/jolt/json-utils/0.1.1/json-utils-0.1.1.jar:/home/alex/Repositories/nifi/nifi-nar-bundles/nifi-standard-bundle/nifi-standard-utils/target/classes:/home/alex/.m2/repository/net/sf/supercsv/super-csv/2.4.0/super-csv-2.4.0.jar:/home/alex/.m2/repository/com/fluenda/parcefone/2.1.0/parcefone-2.1.0.jar:/home/alex/.m2/repository/javax/validation/validation-api/1.1.0.Final/validation-api-1.1.0.Final.jar:/home/alex/.m2/repository/javax/el/javax.el-api/3.0.0/javax.el-api-3.0.0.jar:/home/alex/.m2/repository/com/github/wnameless/json/json-flattener/0.12.0/json-flattener-0.12.0.jar:/home/alex/.m2/repository/com/github/wnameless/json/json-base/2.0.0/json-base-2.0.0.jar:/home/alex/.m2/repository/org/apache/bval/bval-jsr/1.1.2/bval-jsr-1.1.2.jar:/home/alex/.m2/repository/org/apache/bval/bval-core/1.1.2/bval-core-1.1.2.jar:/home/alex/.m2/repository/io/krakens/java-grok/0.1.9/java-grok-0.1.9.jar:/home/alex/.m2/repository/org/apache/calcite/calcite-core/1.27.0/calcite-core-1.27.0.jar:/home/alex/.m2/repository/org/apache/calcite/calcite-linq4j/1.27.0/calcite-linq4j-1.27.0.jar:/home/alex/.m2/repository/com/esri/geometry/esri-geometry-api/2.2.0/esri-geometry-api-2.2.0.jar:/home/alex/.m2/repository/org/apache/calcite/avatica/avatica-core/1.18.0/avatica-core-1.18.0.jar:/home/alex/.m2/repository/org/apache/calcite/avatica/avatica-metrics/1.18.0/avatica-metrics-1.18.0.jar:/home/alex/.m2/repository/com/google/protobuf/protobuf-java/3.6.1/protobuf-java-3.6.1.jar:/home/alex/.m2/repository/org/apiguardian/apiguardian-api/1.1.0/apiguardian-api-1.1.0.jar:/home/alex/.m2/repository/com/fasterxml/jackson/dataformat/jackson-dataformat-yaml/2.10.0/jackson-dataformat-yaml-2.10.0.jar:/home/alex/.m2/repository/org/yaml/snakeyaml/1.29/snakeyaml-1.29.jar:/home/alex/.m2/repository/com/google/uzaygezen/uzaygezen-core/0.2/uzaygezen-core-0.2.jar:/home/alex/.m2/repository/com/yahoo/datasketches/sketches-core/0.9.0/sketches-core-0.9.0.jar:/home/alex/.m2/repository/com/yahoo/datasketches/memory/0.9.0/memory-0.9.0.jar:/home/alex/.m2/repository/net/hydromatic/aggdesigner-algorithm/6.0/aggdesigner-algorithm-6.0.jar:/home/alex/.m2/repository/commons-lang/commons-lang/2.4/commons-lang-2.4.jar:/home/alex/.m2/repository/org/apache/commons/commons-dbcp2/2.6.0/commons-dbcp2-2.6.0.jar:/home/alex/.m2/repository/org/apache/commons/commons-pool2/2.6.1/commons-pool2-2.6.1.jar:/home/alex/.m2/repository/org/codehaus/janino/commons-compiler/3.0.11/commons-compiler-3.0.11.jar:/home/alex/.m2/repository/org/codehaus/janino/janino/3.0.11/janino-3.0.11.jar:/home/alex/Repositories/nifi/nifi-nar-bundles/nifi-standard-services/nifi-schema-registry-service-api/target/classes:/home/alex/Repositories/nifi/nifi-nar-bundles/nifi-extension-utils/nifi-database-utils/target/classes:/home/alex/Repositories/nifi/nifi-nar-bundles/nifi-standard-bundle/nifi-standard-web-test-utils/target/classes:/home/alex/.m2/repository/com/github/stefanbirkner/fake-sftp-server-rule/2.0.1/fake-sftp-server-rule-2.0.1.jar:/home/alex/.m2/repository/com/github/marschall/memoryfilesystem/2.8.0/memoryfilesystem-2.8.0.jar:/home/alex/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/alex/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar:/home/alex/Repositories/nifi/nifi-nar-bundles/nifi-extension-utils/nifi-database-test-utils/target/classes:/home/alex/.m2/repository/org/codehaus/groovy/groovy-json/2.5.14/groovy-json-2.5.14.jar:/home/alex/.m2/repository/org/codehaus/groovy/groovy/2.5.14/groovy-2.5.14.jar:/home/alex/.m2/repository/org/codehaus/groovy/groovy-servlet/2.5.14/groovy-servlet-2.5.14.jar:/home/alex/.m2/repository/org/codehaus/groovy/groovy-templates/2.5.14/groovy-templates-2.5.14.jar:/home/alex/.m2/repository/org/codehaus/groovy/groovy-xml/2.5.14/groovy-xml-2.5.14.jar:/home/alex/.m2/repository/org/hamcrest/hamcrest-all/1.3/hamcrest-all-1.3.jar:/home/alex/.m2/repository/com/squareup/okhttp3/mockwebserver/4.9.2/mockwebserver-4.9.2.jar:/home/alex/.m2/repository/org/jetbrains/kotlin/kotlin-stdlib-jdk8/1.4.10/kotlin-stdlib-jdk8-1.4.10.jar:/home/alex/.m2/repository/org/jetbrains/kotlin/kotlin-stdlib-jdk7/1.4.10/kotlin-stdlib-jdk7-1.4.10.jar:/home/alex/.m2/repository/org/mockito/mockito-inline/3.12.4/mockito-inline-3.12.4.jar:/home/alex/.m2/repository/org/junit/jupiter/junit-jupiter-api/5.7.2/junit-jupiter-api-5.7.2.jar:/home/alex/.m2/repository/org/opentest4j/opentest4j/1.2.0/opentest4j-1.2.0.jar:/home/alex/.m2/repository/org/junit/platform/junit-platform-commons/1.7.2/junit-platform-commons-1.7.2.jar:/home/alex/.m2/repository/org/junit/jupiter/junit-jupiter-engine/5.7.2/junit-jupiter-engine-5.7.2.jar:/home/alex/.m2/repository/org/junit/platform/junit-platform-engine/1.7.2/junit-platform-engine-1.7.2.jar:/home/alex/.m2/repository/org/junit/vintage/junit-vintage-engine/5.7.2/junit-vintage-engine-5.7.2.jar:/home/alex/.m2/repository/org/junit/jupiter/junit-jupiter-params/5.7.2/junit-jupiter-params-5.7.2.jar:/home/alex/.m2/repository/org/mockito/mockito-core/3.11.2/mockito-core-3.11.2.jar:/home/alex/.m2/repository/net/bytebuddy/byte-buddy/1.11.3/byte-buddy-1.11.3.jar:/home/alex/.m2/repository/net/bytebuddy/byte-buddy-agent/1.11.3/byte-buddy-agent-1.11.3.jar:/home/alex/.m2/repository/org/objenesis/objenesis/3.2/objenesis-3.2.jar:/home/alex/.m2/repository/org/mockito/mockito-junit-jupiter/3.11.2/mockito-junit-jupiter-3.11.2.jar:/home/alex/.m2/repository/org/slf4j/slf4j-simple/1.7.32/slf4j-simple-1.7.32.jar:/home/alex/.m2/repository/org/codehaus/groovy/groovy-test/2.5.14/groovy-test-2.5.14.jar:"/>
    <property name="org.slf4j.simpleLogger.log.nifi.processors.standard.TestExecuteSQLRecord" value="debug"/>
    <property name="java.vm.vendor" value="Private Build"/>
    <property name="sun.arch.data.model" value="64"/>
    <property name="java.vendor.url" value="http://java.oracle.com/"/>
    <property name="user.timezone" value="Europe/Lisbon"/>
    <property name="java.vm.specification.version" value="1.8"/>
    <property name="os.name" value="Linux"/>
    <property name="user.country" value="US"/>
    <property name="sun.java.launcher" value="SUN_STANDARD"/>
    <property name="sun.boot.library.path" value="/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64"/>
    <property name="sun.java.command" value="/home/alex/Repositories/nifi/nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/target/surefire/surefirebooter5361507383572708917.jar /home/alex/Repositories/nifi/nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/target/surefire 2024-05-02T01-23-45_285-jvmRun1 surefire2937495179455515110tmp surefire_696557117907135602125tmp"/>
    <property name="org.slf4j.simpleLogger.log.nifi.io.nio" value="debug"/>
    <property name="surefire.test.class.path" value="/home/alex/Repositories/nifi/nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/target/test-classes:/home/alex/Repositories/nifi/nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/target/classes:/home/alex/.m2/repository/org/apache/ftpserver/ftpserver-core/1.1.1/ftpserver-core-1.1.1.jar:/home/alex/.m2/repository/org/apache/ftpserver/ftplet-api/1.1.1/ftplet-api-1.1.1.jar:/home/alex/.m2/repository/org/slf4j/slf4j-api/1.7.32/slf4j-api-1.7.32.jar:/home/alex/.m2/repository/org/apache/mina/mina-core/2.0.16/mina-core-2.0.16.jar:/home/alex/Repositories/nifi/nifi-api/target/classes:/home/alex/Repositories/nifi/nifi-commons/nifi-expression-language/target/classes:/home/alex/.m2/repository/org/antlr/antlr-runtime/3.5.2/antlr-runtime-3.5.2.jar:/home/alex/Repositories/nifi/nifi-commons/nifi-parameter/target/classes:/home/alex/Repositories/nifi/nifi-commons/nifi-uuid5/target/classes:/home/alex/.m2/repository/org/apache/commons/commons-text/1.8/commons-text-1.8.jar:/home/alex/Repositories/nifi/nifi-nar-bundles/nifi-extension-utils/nifi-processor-utils/target/classes:/home/alex/Repositories/nifi/nifi-commons/nifi-security-socket-ssl/target/classes:/home/alex/Repositories/nifi/nifi-nar-bundles/nifi-extension-utils/nifi-event-transport/target/classes:/home/alex/.m2/repository/io/netty/netty-handler/4.1.69.Final/netty-handler-4.1.69.Final.jar:/home/alex/.m2/repository/io/netty/netty-common/4.1.69.Final/netty-common-4.1.69.Final.jar:/home/alex/.m2/repository/io/netty/netty-resolver/4.1.69.Final/netty-resolver-4.1.69.Final.jar:/home/alex/.m2/repository/io/netty/netty-transport/4.1.69.Final/netty-transport-4.1.69.Final.jar:/home/alex/.m2/repository/io/netty/netty-codec/4.1.69.Final/netty-codec-4.1.69.Final.jar:/home/alex/Repositories/nifi/nifi-nar-bundles/nifi-extension-utils/nifi-syslog-utils/target/classes:/home/alex/.m2/repository/com/github/palindromicity/simple-syslog-5424/0.0.16/simple-syslog-5424-0.0.16.jar:/home/alex/.m2/repository/org/antlr/antlr4-runtime/4.7.2/antlr4-runtime-4.7.2.jar:/home/alex/Repositories/nifi/nifi-commons/nifi-utils/target/classes:/home/alex/Repositories/nifi/nifi-commons/nifi-record-path/target/classes:/home/alex/Repositories/nifi/nifi-commons/nifi-properties/target/classes:/home/alex/Repositories/nifi/nifi-commons/nifi-property-utils/target/classes:/home/alex/.m2/repository/com/github/ben-manes/caffeine/caffeine/2.8.1/caffeine-2.8.1.jar:/home/alex/Repositories/nifi/nifi-nar-bundles/nifi-standard-services/nifi-ssl-context-service-api/target/classes:/home/alex/Repositories/nifi/nifi-commons/nifi-security-utils-api/target/classes:/home/alex/Repositories/nifi/nifi-nar-bundles/nifi-standard-services/nifi-lookup-service-api/target/classes:/home/alex/Repositories/nifi/nifi-commons/nifi-flowfile-packager/target/classes:/home/alex/Repositories/nifi/nifi-nar-bundles/nifi-standard-services/nifi-distributed-cache-client-service-api/target/classes:/home/alex/Repositories/nifi/nifi-nar-bundles/nifi-standard-services/nifi-http-context-map-api/target/classes:/home/alex/Repositories/nifi/nifi-nar-bundles/nifi-standard-services/nifi-record-serialization-service-api/target/classes:/home/alex/Repositories/nifi/nifi-nar-bundles/nifi-standard-services/nifi-proxy-configuration-api/target/classes:/home/alex/Repositories/nifi/nifi-commons/nifi-record/target/classes:/home/alex/Repositories/nifi/nifi-nar-bundles/nifi-standard-services/nifi-record-sink-api/target/classes:/home/alex/.m2/repository/commons-io/commons-io/2.10.0/commons-io-2.10.0.jar:/home/alex/.m2/repository/javax/ws/rs/javax.ws.rs-api/2.1/javax.ws.rs-api-2.1.jar:/home/alex/.m2/repository/commons-net/commons-net/3.6/commons-net-3.6.jar:/home/alex/.m2/repository/org/apache/commons/commons-compress/1.21/commons-compress-1.21.jar:/home/alex/.m2/repository/org/apache/commons/commons-lang3/3.9/commons-lang3-3.9.jar:/home/alex/.m2/repository/org/bouncycastle/bcprov-jdk15on/1.69/bcprov-jdk15on-1.69.jar:/home/alex/.m2/repository/org/bouncycastle/bcpg-jdk15on/1.69/bcpg-jdk15on-1.69.jar:/home/alex/.m2/repository/org/bouncycastle/bcpkix-jdk15on/1.69/bcpkix-jdk15on-1.69.jar:/home/alex/.m2/repository/org/bouncycastle/bcutil-jdk15on/1.69/bcutil-jdk15on-1.69.jar:/home/alex/.m2/repository/commons-codec/commons-codec/1.14/commons-codec-1.14.jar:/home/alex/Repositories/nifi/nifi-commons/nifi-security-utils/target/classes:/home/alex/Repositories/nifi/nifi-commons/nifi-security-kms/target/classes:/home/alex/.m2/repository/org/apache/commons/commons-configuration2/2.7/commons-configuration2-2.7.jar:/home/alex/.m2/repository/com/hierynomus/sshj/0.32.0/sshj-0.32.0.jar:/home/alex/.m2/repository/com/jcraft/jzlib/1.1.3/jzlib-1.1.3.jar:/home/alex/.m2/repository/com/hierynomus/asn-one/0.6.0/asn-one-0.6.0.jar:/home/alex/.m2/repository/net/i2p/crypto/eddsa/0.3.0/eddsa-0.3.0.jar:/home/alex/.m2/repository/org/eclipse/jetty/jetty-server/9.4.44.v20210927/jetty-server-9.4.44.v20210927.jar:/home/alex/.m2/repository/javax/servlet/javax.servlet-api/3.1.0/javax.servlet-api-3.1.0.jar:/home/alex/.m2/repository/org/eclipse/jetty/jetty-http/9.4.44.v20210927/jetty-http-9.4.44.v20210927.jar:/home/alex/.m2/repository/org/eclipse/jetty/jetty-util/9.4.44.v20210927/jetty-util-9.4.44.v20210927.jar:/home/alex/.m2/repository/org/eclipse/jetty/jetty-io/9.4.44.v20210927/jetty-io-9.4.44.v20210927.jar:/home/alex/.m2/repository/org/eclipse/jetty/jetty-servlet/9.4.44.v20210927/jetty-servlet-9.4.44.v20210927.jar:/home/alex/.m2/repository/org/eclipse/jetty/jetty-security/9.4.44.v20210927/jetty-security-9.4.44.v20210927.jar:/home/alex/.m2/repository/org/eclipse/jetty/jetty-util-ajax/9.4.44.v20210927/jetty-util-ajax-9.4.44.v20210927.jar:/home/alex/.m2/repository/org/apache/httpcomponents/httpclient/4.5.5/httpclient-4.5.5.jar:/home/alex/.m2/repository/commons-logging/commons-logging/1.2/commons-logging-1.2.jar:/home/alex/.m2/repository/org/apache/httpcomponents/httpcore/4.4.9/httpcore-4.4.9.jar:/home/alex/.m2/repository/jakarta/activation/jakarta.activation-api/2.0.1/jakarta.activation-api-2.0.1.jar:/home/alex/.m2/repository/com/sun/activation/jakarta.activation/2.0.1/jakarta.activation-2.0.1.jar:/home/alex/.m2/repository/jakarta/mail/jakarta.mail-api/2.0.1/jakarta.mail-api-2.0.1.jar:/home/alex/.m2/repository/com/sun/mail/jakarta.mail/2.0.1/jakarta.mail-2.0.1.jar:/home/alex/.m2/repository/com/github/jponge/lzma-java/1.3/lzma-java-1.3.jar:/home/alex/.m2/repository/org/tukaani/xz/1.8/xz-1.8.jar:/home/alex/.m2/repository/net/sf/saxon/Saxon-HE/10.6/Saxon-HE-10.6.jar:/home/alex/Repositories/nifi/nifi-commons/nifi-socket-utils/target/classes:/home/alex/Repositories/nifi/nifi-commons/nifi-logging-utils/target/classes:/home/alex/Repositories/nifi/nifi-nar-bundles/nifi-standard-services/nifi-load-distribution-service-api/target/classes:/home/alex/.m2/repository/javax/jms/javax.jms-api/2.0.1/javax.jms-api-2.0.1.jar:/home/alex/.m2/repository/org/apache/activemq/activemq-client/5.15.15/activemq-client-5.15.15.jar:/home/alex/.m2/repository/org/apache/geronimo/specs/geronimo-jms_1.1_spec/1.1.1/geronimo-jms_1.1_spec-1.1.1.jar:/home/alex/.m2/repository/org/fusesource/hawtbuf/hawtbuf/1.11/hawtbuf-1.11.jar:/home/alex/.m2/repository/org/apache/geronimo/specs/geronimo-j2ee-management_1.1_spec/1.0.1/geronimo-j2ee-management_1.1_spec-1.0.1.jar:/home/alex/.m2/repository/com/jayway/jsonpath/json-path/2.6.0/json-path-2.6.0.jar:/home/alex/.m2/repository/net/minidev/json-smart/2.4.7/json-smart-2.4.7.jar:/home/alex/.m2/repository/net/minidev/accessors-smart/2.4.7/accessors-smart-2.4.7.jar:/home/alex/.m2/repository/org/ow2/asm/asm/9.1/asm-9.1.jar:/home/alex/.m2/repository/org/apache/tika/tika-core/1.26/tika-core-1.26.jar:/home/alex/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.12.3/jackson-databind-2.12.3.jar:/home/alex/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.12.3/jackson-annotations-2.12.3.jar:/home/alex/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.12.3/jackson-core-2.12.3.jar:/home/alex/Repositories/nifi/nifi-nar-bundles/nifi-extension-utils/nifi-record-utils/nifi-avro-record-utils/target/classes:/home/alex/Repositories/nifi/nifi-nar-bundles/nifi-extension-utils/nifi-record-utils/nifi-standard-record-utils/target/classes:/home/alex/.m2/repository/org/apache/avro/avro/1.8.1/avro-1.8.1.jar:/home/alex/.m2/repository/org/codehaus/jackson/jackson-core-asl/1.9.13/jackson-core-asl-1.9.13.jar:/home/alex/.m2/repository/org/codehaus/jackson/jackson-mapper-asl/1.9.13/jackson-mapper-asl-1.9.13.jar:/home/alex/.m2/repository/com/thoughtworks/paranamer/paranamer/2.7/paranamer-2.7.jar:/home/alex/Repositories/nifi/nifi-nar-bundles/nifi-standard-services/nifi-dbcp-service-api/target/classes:/home/alex/.m2/repository/com/squareup/okhttp3/okhttp/4.9.2/okhttp-4.9.2.jar:/home/alex/.m2/repository/com/squareup/okio/okio/2.8.0/okio-2.8.0.jar:/home/alex/.m2/repository/org/jetbrains/kotlin/kotlin-stdlib-common/1.4.0/kotlin-stdlib-common-1.4.0.jar:/home/alex/.m2/repository/org/jetbrains/kotlin/kotlin-stdlib/1.4.10/kotlin-stdlib-1.4.10.jar:/home/alex/.m2/repository/org/jetbrains/annotations/13.0/annotations-13.0.jar:/home/alex/.m2/repository/io/github/rburgst/okhttp-digest/2.5/okhttp-digest-2.5.jar:/home/alex/.m2/repository/at/favre/lib/bcrypt/0.9.0/bcrypt-0.9.0.jar:/home/alex/.m2/repository/at/favre/lib/bytes/1.3.0/bytes-1.3.0.jar:/home/alex/.m2/repository/com/google/guava/guava/28.0-jre/guava-28.0-jre.jar:/home/alex/.m2/repository/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar:/home/alex/.m2/repository/com/google/guava/listenablefuture/9999.0-empty-to-avoid-conflict-with-guava/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar:/home/alex/.m2/repository/com/google/code/findbugs/jsr305/3.0.2/jsr305-3.0.2.jar:/home/alex/.m2/repository/org/checkerframework/checker-qual/2.8.1/checker-qual-2.8.1.jar:/home/alex/.m2/repository/com/google/errorprone/error_prone_annotations/2.3.2/error_prone_annotations-2.3.2.jar:/home/alex/.m2/repository/com/google/j2objc/j2objc-annotations/1.3/j2objc-annotations-1.3.jar:/home/alex/.m2/repository/org/codehaus/mojo/animal-sniffer-annotations/1.17/animal-sniffer-annotations-1.17.jar:/home/alex/Repositories/nifi/nifi-mock/target/classes:/home/alex/Repositories/nifi/nifi-framework-api/target/classes:/home/alex/Repositories/nifi/nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-core-api/target/classes:/home/alex/Repositories/nifi/nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-nar-utils/target/classes:/home/alex/Repositories/nifi/nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-client-dto/target/classes:/home/alex/.m2/repository/io/swagger/swagger-annotations/1.6.0/swagger-annotations-1.6.0.jar:/home/alex/Repositories/nifi/nifi-commons/nifi-site-to-site-client/target/classes:/home/alex/.m2/repository/org/apache/httpcomponents/httpasyncclient/4.1.4/httpasyncclient-4.1.4.jar:/home/alex/.m2/repository/org/apache/httpcomponents/httpcore-nio/4.4.10/httpcore-nio-4.4.10.jar:/home/alex/Repositories/nifi/nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-authorization/target/classes:/home/alex/Repositories/nifi/nifi-registry/nifi-registry-core/nifi-registry-data-model/target/classes:/home/alex/Repositories/nifi/nifi-registry/nifi-registry-core/nifi-registry-revision/nifi-registry-revision-entity-model/target/classes:/home/alex/Repositories/nifi/nifi-registry/nifi-registry-core/nifi-registry-client/target/classes:/home/alex/Repositories/nifi/nifi-registry/nifi-registry-core/nifi-registry-security-utils/target/classes:/home/alex/.m2/repository/org/glassfish/jersey/core/jersey-client/2.33/jersey-client-2.33.jar:/home/alex/.m2/repository/jakarta/ws/rs/jakarta.ws.rs-api/2.1.6/jakarta.ws.rs-api-2.1.6.jar:/home/alex/.m2/repository/org/glassfish/hk2/external/jakarta.inject/2.6.1/jakarta.inject-2.6.1.jar:/home/alex/.m2/repository/org/glassfish/jersey/media/jersey-media-json-jackson/2.33/jersey-media-json-jackson-2.33.jar:/home/alex/.m2/repository/org/glassfish/jersey/ext/jersey-entity-filtering/2.33/jersey-entity-filtering-2.33.jar:/home/alex/.m2/repository/org/glassfish/jersey/inject/jersey-hk2/2.33/jersey-hk2-2.33.jar:/home/alex/.m2/repository/org/glassfish/hk2/hk2-locator/2.6.1/hk2-locator-2.6.1.jar:/home/alex/.m2/repository/org/glassfish/hk2/external/aopalliance-repackaged/2.6.1/aopalliance-repackaged-2.6.1.jar:/home/alex/.m2/repository/org/glassfish/hk2/hk2-api/2.6.1/hk2-api-2.6.1.jar:/home/alex/.m2/repository/org/glassfish/hk2/hk2-utils/2.6.1/hk2-utils-2.6.1.jar:/home/alex/.m2/repository/org/javassist/javassist/3.25.0-GA/javassist-3.25.0-GA.jar:/home/alex/.m2/repository/org/glassfish/jersey/core/jersey-common/2.33/jersey-common-2.33.jar:/home/alex/.m2/repository/jakarta/annotation/jakarta.annotation-api/1.3.5/jakarta.annotation-api-1.3.5.jar:/home/alex/.m2/repository/org/glassfish/hk2/osgi-resource-locator/1.0.3/osgi-resource-locator-1.0.3.jar:/home/alex/.m2/repository/org/glassfish/jersey/media/jersey-media-multipart/2.33/jersey-media-multipart-2.33.jar:/home/alex/.m2/repository/org/jvnet/mimepull/mimepull/1.9.13/mimepull-1.9.13.jar:/home/alex/Repositories/nifi/nifi-commons/nifi-data-provenance-utils/target/classes:/home/alex/Repositories/nifi/nifi-nar-bundles/nifi-standard-services/nifi-distributed-cache-services-bundle/nifi-distributed-cache-client-service/target/classes:/home/alex/Repositories/nifi/nifi-nar-bundles/nifi-standard-services/nifi-distributed-cache-services-bundle/nifi-distributed-cache-protocol/target/classes:/home/alex/.m2/repository/io/netty/netty-buffer/4.1.69.Final/netty-buffer-4.1.69.Final.jar:/home/alex/.m2/repository/com/google/http-client/google-http-client/1.28.0/google-http-client-1.28.0.jar:/home/alex/.m2/repository/io/opencensus/opencensus-api/0.18.0/opencensus-api-0.18.0.jar:/home/alex/.m2/repository/io/grpc/grpc-context/1.14.0/grpc-context-1.14.0.jar:/home/alex/.m2/repository/io/opencensus/opencensus-contrib-http-util/0.18.0/opencensus-contrib-http-util-0.18.0.jar:/home/alex/.m2/repository/org/apache/activemq/activemq-broker/5.15.14/activemq-broker-5.15.14.jar:/home/alex/.m2/repository/org/apache/activemq/activemq-openwire-legacy/5.15.14/activemq-openwire-legacy-5.15.14.jar:/home/alex/Repositories/nifi/nifi-nar-bundles/nifi-standard-services/nifi-ssl-context-bundle/nifi-ssl-context-service/target/classes:/home/alex/Repositories/nifi/nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-standard-prioritizers/target/classes:/home/alex/Repositories/nifi/nifi-nar-bundles/nifi-extension-utils/nifi-record-utils/nifi-mock-record-utils/target/classes:/home/alex/Repositories/nifi/nifi-nar-bundles/nifi-standard-services/nifi-record-serialization-services-bundle/nifi-record-serialization-services/target/classes:/home/alex/.m2/repository/org/apache/commons/commons-csv/1.8/commons-csv-1.8.jar:/home/alex/.m2/repository/com/fasterxml/jackson/dataformat/jackson-dataformat-csv/2.12.3/jackson-dataformat-csv-2.12.3.jar:/home/alex/.m2/repository/net/java/dev/stax-utils/stax-utils/20070216/stax-utils-20070216.jar:/home/alex/Repositories/nifi/nifi-nar-bundles/nifi-standard-services/nifi-lookup-services-bundle/nifi-lookup-services/target/classes:/home/alex/.m2/repository/commons-beanutils/commons-beanutils/1.9.4/commons-beanutils-1.9.4.jar:/home/alex/.m2/repository/commons-collections/commons-collections/3.2.2/commons-collections-3.2.2.jar:/home/alex/.m2/repository/com/maxmind/geoip2/geoip2/2.12.0/geoip2-2.12.0.jar:/home/alex/.m2/repository/com/maxmind/db/maxmind-db/1.2.2/maxmind-db-1.2.2.jar:/home/alex/.m2/repository/org/apache/derby/derby/10.14.2.0/derby-10.14.2.0.jar:/home/alex/.m2/repository/org/xerial/snappy/snappy-java/1.1.7.3/snappy-java-1.1.7.3.jar:/home/alex/.m2/repository/net/lingala/zip4j/zip4j/2.8.0/zip4j-2.8.0.jar:/home/alex/.m2/repository/com/h2database/h2/1.4.187/h2-1.4.187.jar:/home/alex/.m2/repository/org/mockftpserver/MockFtpServer/2.7.1/MockFtpServer-2.7.1.jar:/home/alex/.m2/repository/org/apache/sshd/sshd-core/1.7.0/sshd-core-1.7.0.jar:/home/alex/.m2/repository/com/bazaarvoice/jolt/jolt-core/0.1.1/jolt-core-0.1.1.jar:/home/alex/.m2/repository/javax/inject/javax.inject/1/javax.inject-1.jar:/home/alex/.m2/repository/com/bazaarvoice/jolt/json-utils/0.1.1/json-utils-0.1.1.jar:/home/alex/Repositories/nifi/nifi-nar-bundles/nifi-standard-bundle/nifi-standard-utils/target/classes:/home/alex/.m2/repository/net/sf/supercsv/super-csv/2.4.0/super-csv-2.4.0.jar:/home/alex/.m2/repository/com/fluenda/parcefone/2.1.0/parcefone-2.1.0.jar:/home/alex/.m2/repository/javax/validation/validation-api/1.1.0.Final/validation-api-1.1.0.Final.jar:/home/alex/.m2/repository/javax/el/javax.el-api/3.0.0/javax.el-api-3.0.0.jar:/home/alex/.m2/repository/com/github/wnameless/json/json-flattener/0.12.0/json-flattener-0.12.0.jar:/home/alex/.m2/repository/com/github/wnameless/json/json-base/2.0.0/json-base-2.0.0.jar:/home/alex/.m2/repository/org/apache/bval/bval-jsr/1.1.2/bval-jsr-1.1.2.jar:/home/alex/.m2/repository/org/apache/bval/bval-core/1.1.2/bval-core-1.1.2.jar:/home/alex/.m2/repository/io/krakens/java-grok/0.1.9/java-grok-0.1.9.jar:/home/alex/.m2/repository/org/apache/calcite/calcite-core/1.27.0/calcite-core-1.27.0.jar:/home/alex/.m2/repository/org/apache/calcite/calcite-linq4j/1.27.0/calcite-linq4j-1.27.0.jar:/home/alex/.m2/repository/com/esri/geometry/esri-geometry-api/2.2.0/esri-geometry-api-2.2.0.jar:/home/alex/.m2/repository/org/apache/calcite/avatica/avatica-core/1.18.0/avatica-core-1.18.0.jar:/home/alex/.m2/repository/org/apache/calcite/avatica/avatica-metrics/1.18.0/avatica-metrics-1.18.0.jar:/home/alex/.m2/repository/com/google/protobuf/protobuf-java/3.6.1/protobuf-java-3.6.1.jar:/home/alex/.m2/repository/org/apiguardian/apiguardian-api/1.1.0/apiguardian-api-1.1.0.jar:/home/alex/.m2/repository/com/fasterxml/jackson/dataformat/jackson-dataformat-yaml/2.10.0/jackson-dataformat-yaml-2.10.0.jar:/home/alex/.m2/repository/org/yaml/snakeyaml/1.29/snakeyaml-1.29.jar:/home/alex/.m2/repository/com/google/uzaygezen/uzaygezen-core/0.2/uzaygezen-core-0.2.jar:/home/alex/.m2/repository/com/yahoo/datasketches/sketches-core/0.9.0/sketches-core-0.9.0.jar:/home/alex/.m2/repository/com/yahoo/datasketches/memory/0.9.0/memory-0.9.0.jar:/home/alex/.m2/repository/net/hydromatic/aggdesigner-algorithm/6.0/aggdesigner-algorithm-6.0.jar:/home/alex/.m2/repository/commons-lang/commons-lang/2.4/commons-lang-2.4.jar:/home/alex/.m2/repository/org/apache/commons/commons-dbcp2/2.6.0/commons-dbcp2-2.6.0.jar:/home/alex/.m2/repository/org/apache/commons/commons-pool2/2.6.1/commons-pool2-2.6.1.jar:/home/alex/.m2/repository/org/codehaus/janino/commons-compiler/3.0.11/commons-compiler-3.0.11.jar:/home/alex/.m2/repository/org/codehaus/janino/janino/3.0.11/janino-3.0.11.jar:/home/alex/Repositories/nifi/nifi-nar-bundles/nifi-standard-services/nifi-schema-registry-service-api/target/classes:/home/alex/Repositories/nifi/nifi-nar-bundles/nifi-extension-utils/nifi-database-utils/target/classes:/home/alex/Repositories/nifi/nifi-nar-bundles/nifi-standard-bundle/nifi-standard-web-test-utils/target/classes:/home/alex/.m2/repository/com/github/stefanbirkner/fake-sftp-server-rule/2.0.1/fake-sftp-server-rule-2.0.1.jar:/home/alex/.m2/repository/com/github/marschall/memoryfilesystem/2.8.0/memoryfilesystem-2.8.0.jar:/home/alex/.m2/repository/junit/junit/4.13.2/junit-4.13.2.jar:/home/alex/.m2/repository/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar:/home/alex/Repositories/nifi/nifi-nar-bundles/nifi-extension-utils/nifi-database-test-utils/target/classes:/home/alex/.m2/repository/org/codehaus/groovy/groovy-json/2.5.14/groovy-json-2.5.14.jar:/home/alex/.m2/repository/org/codehaus/groovy/groovy/2.5.14/groovy-2.5.14.jar:/home/alex/.m2/repository/org/codehaus/groovy/groovy-servlet/2.5.14/groovy-servlet-2.5.14.jar:/home/alex/.m2/repository/org/codehaus/groovy/groovy-templates/2.5.14/groovy-templates-2.5.14.jar:/home/alex/.m2/repository/org/codehaus/groovy/groovy-xml/2.5.14/groovy-xml-2.5.14.jar:/home/alex/.m2/repository/org/hamcrest/hamcrest-all/1.3/hamcrest-all-1.3.jar:/home/alex/.m2/repository/com/squareup/okhttp3/mockwebserver/4.9.2/mockwebserver-4.9.2.jar:/home/alex/.m2/repository/org/jetbrains/kotlin/kotlin-stdlib-jdk8/1.4.10/kotlin-stdlib-jdk8-1.4.10.jar:/home/alex/.m2/repository/org/jetbrains/kotlin/kotlin-stdlib-jdk7/1.4.10/kotlin-stdlib-jdk7-1.4.10.jar:/home/alex/.m2/repository/org/mockito/mockito-inline/3.12.4/mockito-inline-3.12.4.jar:/home/alex/.m2/repository/org/junit/jupiter/junit-jupiter-api/5.7.2/junit-jupiter-api-5.7.2.jar:/home/alex/.m2/repository/org/opentest4j/opentest4j/1.2.0/opentest4j-1.2.0.jar:/home/alex/.m2/repository/org/junit/platform/junit-platform-commons/1.7.2/junit-platform-commons-1.7.2.jar:/home/alex/.m2/repository/org/junit/jupiter/junit-jupiter-engine/5.7.2/junit-jupiter-engine-5.7.2.jar:/home/alex/.m2/repository/org/junit/platform/junit-platform-engine/1.7.2/junit-platform-engine-1.7.2.jar:/home/alex/.m2/repository/org/junit/vintage/junit-vintage-engine/5.7.2/junit-vintage-engine-5.7.2.jar:/home/alex/.m2/repository/org/junit/jupiter/junit-jupiter-params/5.7.2/junit-jupiter-params-5.7.2.jar:/home/alex/.m2/repository/org/mockito/mockito-core/3.11.2/mockito-core-3.11.2.jar:/home/alex/.m2/repository/net/bytebuddy/byte-buddy/1.11.3/byte-buddy-1.11.3.jar:/home/alex/.m2/repository/net/bytebuddy/byte-buddy-agent/1.11.3/byte-buddy-agent-1.11.3.jar:/home/alex/.m2/repository/org/objenesis/objenesis/3.2/objenesis-3.2.jar:/home/alex/.m2/repository/org/mockito/mockito-junit-jupiter/3.11.2/mockito-junit-jupiter-3.11.2.jar:/home/alex/.m2/repository/org/slf4j/slf4j-simple/1.7.32/slf4j-simple-1.7.32.jar:/home/alex/.m2/repository/org/codehaus/groovy/groovy-test/2.5.14/groovy-test-2.5.14.jar:"/>
    <property name="sun.cpu.endian" value="little"/>
    <property name="user.home" value="/home/alex"/>
    <property name="user.language" value="en"/>
    <property name="java.specification.vendor" value="Oracle Corporation"/>
    <property name="java.home" value="/usr/lib/jvm/java-8-openjdk-amd64/jre"/>
    <property name="basedir" value="/home/alex/Repositories/nifi/nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors"/>
    <property name="file.separator" value="/"/>
    <property name="line.separator" value="&#10;"/>
    <property name="java.vm.specification.vendor" value="Oracle Corporation"/>
    <property name="java.specification.name" value="Java Platform API Specification"/>
    <property name="derby.stream.error.file" value="target/derby.log"/>
    <property name="org.slf4j.simpleLogger.log.org.apache.nifi" value="TRACE"/>
    <property name="javax.xml.xpath.XPathFactory:http://saxon.sf.net/jaxp/xpath/om" value="net.sf.saxon.xpath.XPathFactoryImpl"/>
    <property name="java.awt.graphicsenv" value="sun.awt.X11GraphicsEnvironment"/>
    <property name="org.slf4j.simpleLogger.log.org.apache.nifi.processors.standard.SQLTransform" value="debug"/>
    <property name="java.awt.headless" value="true"/>
    <property name="org.slf4j.simpleLogger.log.nifi.processors.standard.ExecuteSQLRecord" value="debug"/>
    <property name="org.slf4j.simpleLogger.showDateTime" value="true"/>
    <property name="surefire.real.class.path" value="/home/alex/Repositories/nifi/nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors/target/surefire/surefirebooter5361507383572708917.jar"/>
    <property name="sun.boot.class.path" value="/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/resources.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/rt.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/sunrsasign.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/jsse.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/jce.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/charsets.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/jfr.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/classes"/>
    <property name="sun.management.compiler" value="HotSpot 64-Bit Tiered Compilers"/>
    <property name="org.slf4j.simpleLogger.log.nifi.processors.standard.TestExecuteSQL" value="debug"/>
    <property name="java.runtime.version" value="1.8.0_402-8u402-ga-2ubuntu1~22.04-b06"/>
    <property name="java.net.preferIPv4Stack" value="true"/>
    <property name="user.name" value="alex"/>
    <property name="path.separator" value=":"/>
    <property name="os.version" value="6.5.0-28-generic"/>
    <property name="java.endorsed.dirs" value="/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/endorsed"/>
    <property name="java.runtime.name" value="OpenJDK Runtime Environment"/>
    <property name="org.slf4j.simpleLogger.log.nifi.processors.standard.DistributeLoad" value="debug"/>
    <property name="file.encoding" value="UTF-8"/>
    <property name="org.slf4j.simpleLogger.log.org.apache.nifi.processors.standard" value="TRACE"/>
    <property name="org.slf4j.simpleLogger.log.nifi.processors.standard.ExecuteSQL" value="debug"/>
    <property name="sun.nio.ch.bugLevel" value=""/>
    <property name="java.vm.name" value="OpenJDK 64-Bit Server VM"/>
    <property name="localRepository" value="/home/alex/.m2/repository"/>
    <property name="java.vendor.url.bug" value="http://bugreport.sun.com/bugreport/"/>
    <property name="jetty.git.hash" value="8da83308eeca865e495e53ef315a249d63ba9332"/>
    <property name="java.io.tmpdir" value="/tmp"/>
    <property name="java.version" value="1.8.0_402"/>
    <property name="user.dir" value="/home/alex/Repositories/nifi/nifi-nar-bundles/nifi-standard-bundle/nifi-standard-processors"/>
    <property name="org.slf4j.simpleLogger.log.nifi.processors.standard.TestDetectDuplicate" value="debug"/>
    <property name="os.arch" value="amd64"/>
    <property name="java.vm.specification.name" value="Java Virtual Machine Specification"/>
    <property name="java.awt.printerjob" value="sun.print.PSPrinterJob"/>
    <property name="sun.os.patch.level" value="unknown"/>
    <property name="org.slf4j.simpleLogger.defaultLogLevel" value="info"/>
    <property name="java.library.path" value="/usr/java/packages/lib/amd64:/usr/lib/x86_64-linux-gnu/jni:/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/usr/lib/jni:/lib:/usr/lib"/>
    <property name="java.vm.info" value="mixed mode"/>
    <property name="java.vendor" value="Private Build"/>
    <property name="java.vm.version" value="25.402-b06"/>
    <property name="org.slf4j.simpleLogger.log.nifi.processors.standard.DetectDuplicate" value="debug"/>
    <property name="java.specification.maintenance.version" value="5"/>
    <property name="java.ext.dirs" value="/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext:/usr/java/packages/lib/ext"/>
    <property name="sun.io.unicode.encoding" value="UnicodeLittle"/>
    <property name="java.class.version" value="52.0"/>
  </properties>
  <testcase name="testFailInMiddleWithBadParameterValueAndSupportTransaction" classname="org.apache.nifi.processors.standard.TestPutSQL" time="0.051">
    <system-err><![CDATA[[pool-5268-thread-1] ERROR org.apache.nifi.processors.standard.PutSQL - PutSQL[id=8b6c6273-407a-4940-a6a4-b8f205923480] Failed to update database due to a failed batch update, java.sql.BatchUpdateException: The check constraint 'SQL240502013516250' was violated while performing an INSERT or UPDATE on table '"APP"."PERSONS_AI"'.. There were a total of 1 FlowFiles that failed, 1 that succeeded, and 2 that were not execute and will be routed to retry; : java.sql.BatchUpdateException: The check constraint 'SQL240502013516250' was violated while performing an INSERT or UPDATE on table '"APP"."PERSONS_AI"'.
java.sql.BatchUpdateException: The check constraint 'SQL240502013516250' was violated while performing an INSERT or UPDATE on table '"APP"."PERSONS_AI"'.
	at org.apache.derby.impl.jdbc.EmbedStatement.executeLargeBatch(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedStatement.executeBatch(Unknown Source)
	at org.apache.nifi.processors.standard.PutSQL.lambda$null$8(PutSQL.java:403)
	at org.apache.nifi.processor.util.pattern.ExceptionHandler.execute(ExceptionHandler.java:127)
	at org.apache.nifi.processors.standard.PutSQL.lambda$new$10(PutSQL.java:401)
	at org.apache.nifi.processor.util.pattern.PutGroup.putFlowFiles(PutGroup.java:94)
	at org.apache.nifi.processor.util.pattern.Put.onTrigger(Put.java:103)
	at org.apache.nifi.processors.standard.PutSQL.lambda$onTrigger$19(PutSQL.java:635)
	at org.apache.nifi.processor.util.pattern.PartialFunctions.onTrigger(PartialFunctions.java:120)
	at org.apache.nifi.processor.util.pattern.RollbackOnFailure.onTrigger(RollbackOnFailure.java:184)
	at org.apache.nifi.processors.standard.PutSQL.onTrigger(PutSQL.java:635)
	at org.apache.nifi.util.StandardProcessorTestRunner$RunProcessor.call(StandardProcessorTestRunner.java:284)
	at org.apache.nifi.util.StandardProcessorTestRunner$RunProcessor.call(StandardProcessorTestRunner.java:278)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: org.apache.derby.shared.common.error.DerbySQLIntegrityConstraintViolationException: The check constraint 'SQL240502013516250' was violated while performing an INSERT or UPDATE on table '"APP"."PERSONS_AI"'.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeBatchElement(Unknown Source)
	... 19 more
Caused by: ERROR 23513: The check constraint 'SQL240502013516250' was violated while performing an INSERT or UPDATE on table '"APP"."PERSONS_AI"'.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.iapi.types.SQLBoolean.throwExceptionIfFalse(Unknown Source)
	at org.apache.derby.exe.acc00b5e19x018fx36b7x5f61x00000eecc0200.e1(Unknown Source)
	at org.apache.derby.impl.services.reflect.DirectCall.invoke(Unknown Source)
	at org.apache.derby.impl.sql.execute.InsertResultSet.evaluateCheckConstraints(Unknown Source)
	at org.apache.derby.impl.sql.execute.InsertResultSet.normalInsertCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.InsertResultSet.open(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.executeStmt(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.execute(Unknown Source)
	... 21 more
]]></system-err>
  </testcase>
  <testcase name="testUsingSqlDataTypesWithNegativeValues" classname="org.apache.nifi.processors.standard.TestPutSQL" time="0.019"/>
  <testcase name="testUsingDateValuesEpochAndString" classname="org.apache.nifi.processors.standard.TestPutSQL" time="0.016"/>
  <testcase name="testUsingTimestampValuesWithFormatAttribute" classname="org.apache.nifi.processors.standard.TestPutSQL" time="0.017"/>
  <testcase name="testFailInMiddleWithBadParameterTypeRollbackOnFailure" classname="org.apache.nifi.processors.standard.TestPutSQL" time="0.003">
    <system-err><![CDATA[[pool-5272-thread-1] DEBUG org.apache.nifi.processors.standard.PutSQL - PutSQL[id=7005d60e-5879-400f-b98c-684c0f8942e0] Adjusted InvalidInput to Result{destination=ProcessException, penalty=Yield} based on context rollbackOnFailure=true, processedCount=0, transactional=true
[pool-5272-thread-1] ERROR org.apache.nifi.processors.standard.PutSQL - PutSQL[id=7005d60e-5879-400f-b98c-684c0f8942e0] org.apache.nifi.processors.standard.PutSQL$$Lambda$2020/1547646810@1681aae8 failed to process due to org.apache.nifi.processor.exception.ProcessException: Failed to process FlowFile[1,90536265564798.mockFlowFile,54B] due to java.sql.SQLDataException: Invalid character string format for type INTEGER.; rolling back session: org.apache.nifi.processor.exception.ProcessException: Failed to process FlowFile[1,90536265564798.mockFlowFile,54B] due to java.sql.SQLDataException: Invalid character string format for type INTEGER.
org.apache.nifi.processor.exception.ProcessException: Failed to process FlowFile[1,90536265564798.mockFlowFile,54B] due to java.sql.SQLDataException: Invalid character string format for type INTEGER.
	at org.apache.nifi.processor.util.pattern.ExceptionHandler.lambda$createOnGroupError$2(ExceptionHandler.java:226)
	at org.apache.nifi.processor.util.pattern.ExceptionHandler.lambda$createOnError$1(ExceptionHandler.java:179)
	at org.apache.nifi.processor.util.pattern.ExceptionHandler$OnError.lambda$andThen$0(ExceptionHandler.java:54)
	at org.apache.nifi.processor.util.pattern.ExceptionHandler$OnError.lambda$andThen$0(ExceptionHandler.java:54)
	at org.apache.nifi.processor.util.pattern.ExceptionHandler.execute(ExceptionHandler.java:148)
	at org.apache.nifi.processors.standard.PutSQL.lambda$new$5(PutSQL.java:342)
	at org.apache.nifi.processors.standard.PutSQL.lambda$new$7(PutSQL.java:387)
	at org.apache.nifi.processor.util.pattern.PutGroup.putFlowFiles(PutGroup.java:91)
	at org.apache.nifi.processor.util.pattern.Put.onTrigger(Put.java:103)
	at org.apache.nifi.processors.standard.PutSQL.lambda$onTrigger$19(PutSQL.java:635)
	at org.apache.nifi.processor.util.pattern.PartialFunctions.onTrigger(PartialFunctions.java:120)
	at org.apache.nifi.processor.util.pattern.RollbackOnFailure.onTrigger(RollbackOnFailure.java:184)
	at org.apache.nifi.processors.standard.PutSQL.onTrigger(PutSQL.java:635)
	at org.apache.nifi.util.StandardProcessorTestRunner$RunProcessor.call(StandardProcessorTestRunner.java:284)
	at org.apache.nifi.util.StandardProcessorTestRunner$RunProcessor.call(StandardProcessorTestRunner.java:278)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.sql.SQLDataException: Invalid character string format for type INTEGER.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedResultSet.noStateChangeException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.setString(Unknown Source)
	at org.apache.nifi.util.db.JdbcCommon.setParameter(JdbcCommon.java:850)
	at org.apache.nifi.util.db.JdbcCommon.setParameters(JdbcCommon.java:696)
	at org.apache.nifi.processors.standard.PutSQL.lambda$null$4(PutSQL.java:344)
	at org.apache.nifi.processor.util.pattern.ExceptionHandler.execute(ExceptionHandler.java:127)
	... 16 more
Caused by: ERROR 22018: Invalid character string format for type INTEGER.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.iapi.types.DataType.invalidFormat(Unknown Source)
	at org.apache.derby.iapi.types.SQLInteger.setValue(Unknown Source)
	... 21 more
[pool-5272-thread-1] WARN org.apache.nifi.processors.standard.PutSQL - PutSQL[id=7005d60e-5879-400f-b98c-684c0f8942e0] Administratively yielding org.apache.nifi.processors.standard.PutSQL after rolling back due to org.apache.nifi.processor.exception.ProcessException: Failed to process FlowFile[1,90536265564798.mockFlowFile,54B] due to java.sql.SQLDataException: Invalid character string format for type INTEGER.: org.apache.nifi.processor.exception.ProcessException: Failed to process FlowFile[1,90536265564798.mockFlowFile,54B] due to java.sql.SQLDataException: Invalid character string format for type INTEGER.
[pool-5272-thread-1] WARN org.apache.nifi.processors.standard.PutSQL - 
org.apache.nifi.processor.exception.ProcessException: Failed to process FlowFile[1,90536265564798.mockFlowFile,54B] due to java.sql.SQLDataException: Invalid character string format for type INTEGER.
	at org.apache.nifi.processor.util.pattern.ExceptionHandler.lambda$createOnGroupError$2(ExceptionHandler.java:226)
	at org.apache.nifi.processor.util.pattern.ExceptionHandler.lambda$createOnError$1(ExceptionHandler.java:179)
	at org.apache.nifi.processor.util.pattern.ExceptionHandler$OnError.lambda$andThen$0(ExceptionHandler.java:54)
	at org.apache.nifi.processor.util.pattern.ExceptionHandler$OnError.lambda$andThen$0(ExceptionHandler.java:54)
	at org.apache.nifi.processor.util.pattern.ExceptionHandler.execute(ExceptionHandler.java:148)
	at org.apache.nifi.processors.standard.PutSQL.lambda$new$5(PutSQL.java:342)
	at org.apache.nifi.processors.standard.PutSQL.lambda$new$7(PutSQL.java:387)
	at org.apache.nifi.processor.util.pattern.PutGroup.putFlowFiles(PutGroup.java:91)
	at org.apache.nifi.processor.util.pattern.Put.onTrigger(Put.java:103)
	at org.apache.nifi.processors.standard.PutSQL.lambda$onTrigger$19(PutSQL.java:635)
	at org.apache.nifi.processor.util.pattern.PartialFunctions.onTrigger(PartialFunctions.java:120)
	at org.apache.nifi.processor.util.pattern.RollbackOnFailure.onTrigger(RollbackOnFailure.java:184)
	at org.apache.nifi.processors.standard.PutSQL.onTrigger(PutSQL.java:635)
	at org.apache.nifi.util.StandardProcessorTestRunner$RunProcessor.call(StandardProcessorTestRunner.java:284)
	at org.apache.nifi.util.StandardProcessorTestRunner$RunProcessor.call(StandardProcessorTestRunner.java:278)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.sql.SQLDataException: Invalid character string format for type INTEGER.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedResultSet.noStateChangeException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.setString(Unknown Source)
	at org.apache.nifi.util.db.JdbcCommon.setParameter(JdbcCommon.java:850)
	at org.apache.nifi.util.db.JdbcCommon.setParameters(JdbcCommon.java:696)
	at org.apache.nifi.processors.standard.PutSQL.lambda$null$4(PutSQL.java:344)
	at org.apache.nifi.processor.util.pattern.ExceptionHandler.execute(ExceptionHandler.java:127)
	... 16 more
Caused by: ERROR 22018: Invalid character string format for type INTEGER.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.iapi.types.DataType.invalidFormat(Unknown Source)
	at org.apache.derby.iapi.types.SQLInteger.setValue(Unknown Source)
	... 21 more
]]></system-err>
  </testcase>
  <testcase name="testInvalidStatementRollbackOnFailure" classname="org.apache.nifi.processors.standard.TestPutSQL" time="0.027">
    <system-err><![CDATA[[pool-5273-thread-1] DEBUG org.apache.nifi.processors.standard.PutSQL - PutSQL[id=2c6a1aa2-8257-4c78-a78f-eedf86202700] Adjusted InvalidInput to Result{destination=ProcessException, penalty=Yield} based on context rollbackOnFailure=true, processedCount=0, transactional=true
[pool-5273-thread-1] ERROR org.apache.nifi.processors.standard.PutSQL - PutSQL[id=2c6a1aa2-8257-4c78-a78f-eedf86202700] org.apache.nifi.processors.standard.PutSQL$$Lambda$2020/1547646810@28f7f160 failed to process due to org.apache.nifi.processor.exception.ProcessException: Failed to process FlowFile[0,90536287458377.mockFlowFile,106B] due to java.sql.SQLSyntaxErrorException: Syntax error: Encountered ";" at line 1, column 54.; rolling back session: org.apache.nifi.processor.exception.ProcessException: Failed to process FlowFile[0,90536287458377.mockFlowFile,106B] due to java.sql.SQLSyntaxErrorException: Syntax error: Encountered ";" at line 1, column 54.
org.apache.nifi.processor.exception.ProcessException: Failed to process FlowFile[0,90536287458377.mockFlowFile,106B] due to java.sql.SQLSyntaxErrorException: Syntax error: Encountered ";" at line 1, column 54.
	at org.apache.nifi.processor.util.pattern.ExceptionHandler.lambda$createOnGroupError$2(ExceptionHandler.java:226)
	at org.apache.nifi.processor.util.pattern.ExceptionHandler.lambda$createOnError$1(ExceptionHandler.java:179)
	at org.apache.nifi.processor.util.pattern.ExceptionHandler$OnError.lambda$andThen$0(ExceptionHandler.java:54)
	at org.apache.nifi.processor.util.pattern.ExceptionHandler$OnError.lambda$andThen$0(ExceptionHandler.java:54)
	at org.apache.nifi.processor.util.pattern.ExceptionHandler.execute(ExceptionHandler.java:148)
	at org.apache.nifi.processors.standard.PutSQL.lambda$new$5(PutSQL.java:342)
	at org.apache.nifi.processors.standard.PutSQL.lambda$new$7(PutSQL.java:387)
	at org.apache.nifi.processor.util.pattern.PutGroup.putFlowFiles(PutGroup.java:91)
	at org.apache.nifi.processor.util.pattern.Put.onTrigger(Put.java:103)
	at org.apache.nifi.processors.standard.PutSQL.lambda$onTrigger$19(PutSQL.java:635)
	at org.apache.nifi.processor.util.pattern.PartialFunctions.onTrigger(PartialFunctions.java:120)
	at org.apache.nifi.processor.util.pattern.RollbackOnFailure.onTrigger(RollbackOnFailure.java:184)
	at org.apache.nifi.processors.standard.PutSQL.onTrigger(PutSQL.java:635)
	at org.apache.nifi.util.StandardProcessorTestRunner$RunProcessor.call(StandardProcessorTestRunner.java:284)
	at org.apache.nifi.util.StandardProcessorTestRunner$RunProcessor.call(StandardProcessorTestRunner.java:278)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.sql.SQLSyntaxErrorException: Syntax error: Encountered ";" at line 1, column 54.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement42.<init>(Unknown Source)
	at org.apache.derby.jdbc.Driver42.newEmbedPreparedStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.prepareStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.prepareStatement(Unknown Source)
	at org.apache.nifi.processors.standard.PutSQL$StatementFlowFileEnclosure.getCachedStatement(PutSQL.java:1014)
	at org.apache.nifi.processors.standard.PutSQL.lambda$null$4(PutSQL.java:343)
	at org.apache.nifi.processor.util.pattern.ExceptionHandler.execute(ExceptionHandler.java:127)
	... 16 more
Caused by: ERROR 42X01: Syntax error: Encountered ";" at line 1, column 54.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.sql.compile.ParserImpl.parseStatementOrSearchCondition(Unknown Source)
	at org.apache.derby.impl.sql.compile.ParserImpl.parseStatement(Unknown Source)
	at org.apache.derby.impl.sql.GenericStatement.prepMinion(Unknown Source)
	at org.apache.derby.impl.sql.GenericStatement.prepare(Unknown Source)
	at org.apache.derby.impl.sql.conn.GenericLanguageConnectionContext.prepareInternalStatement(Unknown Source)
	... 24 more
[pool-5273-thread-1] WARN org.apache.nifi.processors.standard.PutSQL - PutSQL[id=2c6a1aa2-8257-4c78-a78f-eedf86202700] Administratively yielding org.apache.nifi.processors.standard.PutSQL after rolling back due to org.apache.nifi.processor.exception.ProcessException: Failed to process FlowFile[0,90536287458377.mockFlowFile,106B] due to java.sql.SQLSyntaxErrorException: Syntax error: Encountered ";" at line 1, column 54.: org.apache.nifi.processor.exception.ProcessException: Failed to process FlowFile[0,90536287458377.mockFlowFile,106B] due to java.sql.SQLSyntaxErrorException: Syntax error: Encountered ";" at line 1, column 54.
[pool-5273-thread-1] WARN org.apache.nifi.processors.standard.PutSQL - 
org.apache.nifi.processor.exception.ProcessException: Failed to process FlowFile[0,90536287458377.mockFlowFile,106B] due to java.sql.SQLSyntaxErrorException: Syntax error: Encountered ";" at line 1, column 54.
	at org.apache.nifi.processor.util.pattern.ExceptionHandler.lambda$createOnGroupError$2(ExceptionHandler.java:226)
	at org.apache.nifi.processor.util.pattern.ExceptionHandler.lambda$createOnError$1(ExceptionHandler.java:179)
	at org.apache.nifi.processor.util.pattern.ExceptionHandler$OnError.lambda$andThen$0(ExceptionHandler.java:54)
	at org.apache.nifi.processor.util.pattern.ExceptionHandler$OnError.lambda$andThen$0(ExceptionHandler.java:54)
	at org.apache.nifi.processor.util.pattern.ExceptionHandler.execute(ExceptionHandler.java:148)
	at org.apache.nifi.processors.standard.PutSQL.lambda$new$5(PutSQL.java:342)
	at org.apache.nifi.processors.standard.PutSQL.lambda$new$7(PutSQL.java:387)
	at org.apache.nifi.processor.util.pattern.PutGroup.putFlowFiles(PutGroup.java:91)
	at org.apache.nifi.processor.util.pattern.Put.onTrigger(Put.java:103)
	at org.apache.nifi.processors.standard.PutSQL.lambda$onTrigger$19(PutSQL.java:635)
	at org.apache.nifi.processor.util.pattern.PartialFunctions.onTrigger(PartialFunctions.java:120)
	at org.apache.nifi.processor.util.pattern.RollbackOnFailure.onTrigger(RollbackOnFailure.java:184)
	at org.apache.nifi.processors.standard.PutSQL.onTrigger(PutSQL.java:635)
	at org.apache.nifi.util.StandardProcessorTestRunner$RunProcessor.call(StandardProcessorTestRunner.java:284)
	at org.apache.nifi.util.StandardProcessorTestRunner$RunProcessor.call(StandardProcessorTestRunner.java:278)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.sql.SQLSyntaxErrorException: Syntax error: Encountered ";" at line 1, column 54.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement42.<init>(Unknown Source)
	at org.apache.derby.jdbc.Driver42.newEmbedPreparedStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.prepareStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.prepareStatement(Unknown Source)
	at org.apache.nifi.processors.standard.PutSQL$StatementFlowFileEnclosure.getCachedStatement(PutSQL.java:1014)
	at org.apache.nifi.processors.standard.PutSQL.lambda$null$4(PutSQL.java:343)
	at org.apache.nifi.processor.util.pattern.ExceptionHandler.execute(ExceptionHandler.java:127)
	... 16 more
Caused by: ERROR 42X01: Syntax error: Encountered ";" at line 1, column 54.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.sql.compile.ParserImpl.parseStatementOrSearchCondition(Unknown Source)
	at org.apache.derby.impl.sql.compile.ParserImpl.parseStatement(Unknown Source)
	at org.apache.derby.impl.sql.GenericStatement.prepMinion(Unknown Source)
	at org.apache.derby.impl.sql.GenericStatement.prepare(Unknown Source)
	at org.apache.derby.impl.sql.conn.GenericLanguageConnectionContext.prepareInternalStatement(Unknown Source)
	... 24 more
]]></system-err>
  </testcase>
  <testcase name="testMultipleStatementsWithinFlowFile" classname="org.apache.nifi.processors.standard.TestPutSQL" time="0.021">
    <system-err><![CDATA[[pool-5274-thread-1] ERROR org.apache.nifi.processors.standard.PutSQL - PutSQL[id=60e35491-3c33-488f-941f-0b2bdee0f25b] Failed to update database for FlowFile[0,90536312631102.mockFlowFile,100B] due to java.sql.SQLSyntaxErrorException: Syntax error: Encountered ";" at line 1, column 54.; routing to failure: java.sql.SQLSyntaxErrorException: Syntax error: Encountered ";" at line 1, column 54.
java.sql.SQLSyntaxErrorException: Syntax error: Encountered ";" at line 1, column 54.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement42.<init>(Unknown Source)
	at org.apache.derby.jdbc.Driver42.newEmbedPreparedStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.prepareStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.prepareStatement(Unknown Source)
	at org.apache.nifi.processors.standard.PutSQL$StatementFlowFileEnclosure.getCachedStatement(PutSQL.java:1014)
	at org.apache.nifi.processors.standard.PutSQL.lambda$null$4(PutSQL.java:343)
	at org.apache.nifi.processor.util.pattern.ExceptionHandler.execute(ExceptionHandler.java:127)
	at org.apache.nifi.processors.standard.PutSQL.lambda$new$5(PutSQL.java:342)
	at org.apache.nifi.processors.standard.PutSQL.lambda$new$7(PutSQL.java:387)
	at org.apache.nifi.processor.util.pattern.PutGroup.putFlowFiles(PutGroup.java:91)
	at org.apache.nifi.processor.util.pattern.Put.onTrigger(Put.java:103)
	at org.apache.nifi.processors.standard.PutSQL.lambda$onTrigger$19(PutSQL.java:635)
	at org.apache.nifi.processor.util.pattern.PartialFunctions.onTrigger(PartialFunctions.java:120)
	at org.apache.nifi.processor.util.pattern.RollbackOnFailure.onTrigger(RollbackOnFailure.java:184)
	at org.apache.nifi.processors.standard.PutSQL.onTrigger(PutSQL.java:635)
	at org.apache.nifi.util.StandardProcessorTestRunner$RunProcessor.call(StandardProcessorTestRunner.java:284)
	at org.apache.nifi.util.StandardProcessorTestRunner$RunProcessor.call(StandardProcessorTestRunner.java:278)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: ERROR 42X01: Syntax error: Encountered ";" at line 1, column 54.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.sql.compile.ParserImpl.parseStatementOrSearchCondition(Unknown Source)
	at org.apache.derby.impl.sql.compile.ParserImpl.parseStatement(Unknown Source)
	at org.apache.derby.impl.sql.GenericStatement.prepMinion(Unknown Source)
	at org.apache.derby.impl.sql.GenericStatement.prepare(Unknown Source)
	at org.apache.derby.impl.sql.conn.GenericLanguageConnectionContext.prepareInternalStatement(Unknown Source)
	... 24 more
[pool-5274-thread-1] ERROR org.apache.nifi.processors.standard.PutSQL - PutSQL[id=60e35491-3c33-488f-941f-0b2bdee0f25b] Failed to update database for [] due to java.sql.SQLSyntaxErrorException: Syntax error: Encountered ";" at line 1, column 54.; routing to failure: java.sql.SQLSyntaxErrorException: Syntax error: Encountered ";" at line 1, column 54.
java.sql.SQLSyntaxErrorException: Syntax error: Encountered ";" at line 1, column 54.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement42.<init>(Unknown Source)
	at org.apache.derby.jdbc.Driver42.newEmbedPreparedStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.prepareStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.prepareStatement(Unknown Source)
	at org.apache.nifi.processors.standard.PutSQL$StatementFlowFileEnclosure.getCachedStatement(PutSQL.java:1014)
	at org.apache.nifi.processors.standard.PutSQL.lambda$null$8(PutSQL.java:402)
	at org.apache.nifi.processor.util.pattern.ExceptionHandler.execute(ExceptionHandler.java:127)
	at org.apache.nifi.processors.standard.PutSQL.lambda$new$10(PutSQL.java:401)
	at org.apache.nifi.processor.util.pattern.PutGroup.putFlowFiles(PutGroup.java:94)
	at org.apache.nifi.processor.util.pattern.Put.onTrigger(Put.java:103)
	at org.apache.nifi.processors.standard.PutSQL.lambda$onTrigger$19(PutSQL.java:635)
	at org.apache.nifi.processor.util.pattern.PartialFunctions.onTrigger(PartialFunctions.java:120)
	at org.apache.nifi.processor.util.pattern.RollbackOnFailure.onTrigger(RollbackOnFailure.java:184)
	at org.apache.nifi.processors.standard.PutSQL.onTrigger(PutSQL.java:635)
	at org.apache.nifi.util.StandardProcessorTestRunner$RunProcessor.call(StandardProcessorTestRunner.java:284)
	at org.apache.nifi.util.StandardProcessorTestRunner$RunProcessor.call(StandardProcessorTestRunner.java:278)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: ERROR 42X01: Syntax error: Encountered ";" at line 1, column 54.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.sql.compile.ParserImpl.parseStatementOrSearchCondition(Unknown Source)
	at org.apache.derby.impl.sql.compile.ParserImpl.parseStatement(Unknown Source)
	at org.apache.derby.impl.sql.GenericStatement.prepMinion(Unknown Source)
	at org.apache.derby.impl.sql.GenericStatement.prepare(Unknown Source)
	at org.apache.derby.impl.sql.conn.GenericLanguageConnectionContext.prepareInternalStatement(Unknown Source)
	... 23 more
]]></system-err>
  </testcase>
  <testcase name="testFailInMiddleWithBadStatementAndSupportTransaction" classname="org.apache.nifi.processors.standard.TestPutSQL" time="0.018">
    <system-err><![CDATA[[pool-5275-thread-1] ERROR org.apache.nifi.processors.standard.PutSQL - PutSQL[id=0bb240a2-4b16-4024-9b98-c21198a4b756] Failed to update database for FlowFile[1,90536317733796.mockFlowFile,22B] due to java.sql.SQLSyntaxErrorException: Syntax error: Encountered "<EOF>" at line 1, column 22.; routing to failure: java.sql.SQLSyntaxErrorException: Syntax error: Encountered "<EOF>" at line 1, column 22.
java.sql.SQLSyntaxErrorException: Syntax error: Encountered "<EOF>" at line 1, column 22.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement42.<init>(Unknown Source)
	at org.apache.derby.jdbc.Driver42.newEmbedPreparedStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.prepareStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.prepareStatement(Unknown Source)
	at org.apache.nifi.processors.standard.PutSQL$StatementFlowFileEnclosure.getCachedStatement(PutSQL.java:1014)
	at org.apache.nifi.processors.standard.PutSQL.lambda$null$4(PutSQL.java:343)
	at org.apache.nifi.processor.util.pattern.ExceptionHandler.execute(ExceptionHandler.java:127)
	at org.apache.nifi.processors.standard.PutSQL.lambda$new$5(PutSQL.java:342)
	at org.apache.nifi.processors.standard.PutSQL.lambda$new$7(PutSQL.java:387)
	at org.apache.nifi.processor.util.pattern.PutGroup.putFlowFiles(PutGroup.java:91)
	at org.apache.nifi.processor.util.pattern.Put.onTrigger(Put.java:103)
	at org.apache.nifi.processors.standard.PutSQL.lambda$onTrigger$19(PutSQL.java:635)
	at org.apache.nifi.processor.util.pattern.PartialFunctions.onTrigger(PartialFunctions.java:120)
	at org.apache.nifi.processor.util.pattern.RollbackOnFailure.onTrigger(RollbackOnFailure.java:184)
	at org.apache.nifi.processors.standard.PutSQL.onTrigger(PutSQL.java:635)
	at org.apache.nifi.util.StandardProcessorTestRunner$RunProcessor.call(StandardProcessorTestRunner.java:284)
	at org.apache.nifi.util.StandardProcessorTestRunner$RunProcessor.call(StandardProcessorTestRunner.java:278)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: ERROR 42X01: Syntax error: Encountered "<EOF>" at line 1, column 22.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.sql.compile.ParserImpl.parseStatementOrSearchCondition(Unknown Source)
	at org.apache.derby.impl.sql.compile.ParserImpl.parseStatement(Unknown Source)
	at org.apache.derby.impl.sql.GenericStatement.prepMinion(Unknown Source)
	at org.apache.derby.impl.sql.GenericStatement.prepare(Unknown Source)
	at org.apache.derby.impl.sql.conn.GenericLanguageConnectionContext.prepareInternalStatement(Unknown Source)
	... 24 more
[pool-5275-thread-1] ERROR org.apache.nifi.processors.standard.PutSQL - PutSQL[id=0bb240a2-4b16-4024-9b98-c21198a4b756] Failed to update database for [] due to java.sql.SQLSyntaxErrorException: Syntax error: Encountered "<EOF>" at line 1, column 22.; routing to failure: java.sql.SQLSyntaxErrorException: Syntax error: Encountered "<EOF>" at line 1, column 22.
java.sql.SQLSyntaxErrorException: Syntax error: Encountered "<EOF>" at line 1, column 22.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement42.<init>(Unknown Source)
	at org.apache.derby.jdbc.Driver42.newEmbedPreparedStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.prepareStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.prepareStatement(Unknown Source)
	at org.apache.nifi.processors.standard.PutSQL$StatementFlowFileEnclosure.getCachedStatement(PutSQL.java:1014)
	at org.apache.nifi.processors.standard.PutSQL.lambda$null$8(PutSQL.java:402)
	at org.apache.nifi.processor.util.pattern.ExceptionHandler.execute(ExceptionHandler.java:127)
	at org.apache.nifi.processors.standard.PutSQL.lambda$new$10(PutSQL.java:401)
	at org.apache.nifi.processor.util.pattern.PutGroup.putFlowFiles(PutGroup.java:94)
	at org.apache.nifi.processor.util.pattern.Put.onTrigger(Put.java:103)
	at org.apache.nifi.processors.standard.PutSQL.lambda$onTrigger$19(PutSQL.java:635)
	at org.apache.nifi.processor.util.pattern.PartialFunctions.onTrigger(PartialFunctions.java:120)
	at org.apache.nifi.processor.util.pattern.RollbackOnFailure.onTrigger(RollbackOnFailure.java:184)
	at org.apache.nifi.processors.standard.PutSQL.onTrigger(PutSQL.java:635)
	at org.apache.nifi.util.StandardProcessorTestRunner$RunProcessor.call(StandardProcessorTestRunner.java:284)
	at org.apache.nifi.util.StandardProcessorTestRunner$RunProcessor.call(StandardProcessorTestRunner.java:278)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: ERROR 42X01: Syntax error: Encountered "<EOF>" at line 1, column 22.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.sql.compile.ParserImpl.parseStatementOrSearchCondition(Unknown Source)
	at org.apache.derby.impl.sql.compile.ParserImpl.parseStatement(Unknown Source)
	at org.apache.derby.impl.sql.GenericStatement.prepMinion(Unknown Source)
	at org.apache.derby.impl.sql.GenericStatement.prepare(Unknown Source)
	at org.apache.derby.impl.sql.conn.GenericLanguageConnectionContext.prepareInternalStatement(Unknown Source)
	... 23 more
]]></system-err>
  </testcase>
  <testcase name="testMultipleFlowFilesSuccessfulInTransactionRollBackOnFailure" classname="org.apache.nifi.processors.standard.TestPutSQL" time="0.019">
    <system-err><![CDATA[[pool-5276-thread-1] DEBUG org.apache.nifi.processors.standard.PutSQL - PutSQL[id=087091b2-5636-4577-aa13-ff19aca06fe2] Not enough FlowFiles for transaction. Returning all FlowFiles to queue
[pool-5276-thread-1] DEBUG org.apache.nifi.processors.standard.PutSQL - PutSQL[id=087091b2-5636-4577-aa13-ff19aca06fe2] No incoming FlowFiles.
]]></system-err>
  </testcase>
  <testcase name="testUsingDateTimeValuesWithFormatAttribute" classname="org.apache.nifi.processors.standard.TestPutSQL" time="0.021"/>
  <testcase name="testBitType" classname="org.apache.nifi.processors.standard.TestPutSQL" time="0.015"/>
  <testcase name="testTransactionalFlowFileFilter" classname="org.apache.nifi.processors.standard.TestPutSQL" time="0.001"/>
  <testcase name="testRetryableFailureRollbackOnFailure" classname="org.apache.nifi.processors.standard.TestPutSQL" time="0.003">
    <system-err><![CDATA[[pool-5279-thread-1] DEBUG org.apache.nifi.processors.standard.PutSQL - PutSQL[id=8d07b016-ecb8-4ef9-92ef-c50d5a542103] Adjusted TemporalFailure to Result{destination=ProcessException, penalty=Yield} based on context rollbackOnFailure=true, processedCount=0, transactional=true
[pool-5279-thread-1] ERROR org.apache.nifi.processors.standard.PutSQL - PutSQL[id=8d07b016-ecb8-4ef9-92ef-c50d5a542103] org.apache.nifi.processors.standard.PutSQL$$Lambda$2020/1547646810@1a7b51e7 failed to process due to org.apache.nifi.processor.exception.ProcessException: Failed to process FlowFile[0,90536393309616.mockFlowFile,100B] due to java.sql.SQLException: Unit Test Generated SQLException; rolling back session: org.apache.nifi.processor.exception.ProcessException: Failed to process FlowFile[0,90536393309616.mockFlowFile,100B] due to java.sql.SQLException: Unit Test Generated SQLException
org.apache.nifi.processor.exception.ProcessException: Failed to process FlowFile[0,90536393309616.mockFlowFile,100B] due to java.sql.SQLException: Unit Test Generated SQLException
	at org.apache.nifi.processor.util.pattern.ExceptionHandler.lambda$createOnGroupError$2(ExceptionHandler.java:226)
	at org.apache.nifi.processor.util.pattern.ExceptionHandler.lambda$createOnError$1(ExceptionHandler.java:179)
	at org.apache.nifi.processor.util.pattern.ExceptionHandler$OnError.lambda$andThen$0(ExceptionHandler.java:54)
	at org.apache.nifi.processor.util.pattern.ExceptionHandler$OnError.lambda$andThen$0(ExceptionHandler.java:54)
	at org.apache.nifi.processor.util.pattern.ExceptionHandler.execute(ExceptionHandler.java:148)
	at org.apache.nifi.processors.standard.PutSQL.lambda$new$5(PutSQL.java:342)
	at org.apache.nifi.processors.standard.PutSQL.lambda$new$7(PutSQL.java:387)
	at org.apache.nifi.processor.util.pattern.PutGroup.putFlowFiles(PutGroup.java:91)
	at org.apache.nifi.processor.util.pattern.Put.onTrigger(Put.java:103)
	at org.apache.nifi.processors.standard.PutSQL.lambda$onTrigger$19(PutSQL.java:635)
	at org.apache.nifi.processor.util.pattern.PartialFunctions.onTrigger(PartialFunctions.java:120)
	at org.apache.nifi.processor.util.pattern.RollbackOnFailure.onTrigger(RollbackOnFailure.java:184)
	at org.apache.nifi.processors.standard.PutSQL.onTrigger(PutSQL.java:635)
	at org.apache.nifi.util.StandardProcessorTestRunner$RunProcessor.call(StandardProcessorTestRunner.java:284)
	at org.apache.nifi.util.StandardProcessorTestRunner$RunProcessor.call(StandardProcessorTestRunner.java:278)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.sql.SQLException: Unit Test Generated SQLException
	at org.apache.nifi.processors.standard.PutSQL$StatementFlowFileEnclosure.getCachedStatement(PutSQL.java:1014)
	at org.apache.nifi.processors.standard.PutSQL.lambda$null$4(PutSQL.java:343)
	at org.apache.nifi.processor.util.pattern.ExceptionHandler.execute(ExceptionHandler.java:127)
	... 16 more
[pool-5279-thread-1] WARN org.apache.nifi.processors.standard.PutSQL - PutSQL[id=8d07b016-ecb8-4ef9-92ef-c50d5a542103] Administratively yielding org.apache.nifi.processors.standard.PutSQL after rolling back due to org.apache.nifi.processor.exception.ProcessException: Failed to process FlowFile[0,90536393309616.mockFlowFile,100B] due to java.sql.SQLException: Unit Test Generated SQLException: org.apache.nifi.processor.exception.ProcessException: Failed to process FlowFile[0,90536393309616.mockFlowFile,100B] due to java.sql.SQLException: Unit Test Generated SQLException
[pool-5279-thread-1] WARN org.apache.nifi.processors.standard.PutSQL - 
org.apache.nifi.processor.exception.ProcessException: Failed to process FlowFile[0,90536393309616.mockFlowFile,100B] due to java.sql.SQLException: Unit Test Generated SQLException
	at org.apache.nifi.processor.util.pattern.ExceptionHandler.lambda$createOnGroupError$2(ExceptionHandler.java:226)
	at org.apache.nifi.processor.util.pattern.ExceptionHandler.lambda$createOnError$1(ExceptionHandler.java:179)
	at org.apache.nifi.processor.util.pattern.ExceptionHandler$OnError.lambda$andThen$0(ExceptionHandler.java:54)
	at org.apache.nifi.processor.util.pattern.ExceptionHandler$OnError.lambda$andThen$0(ExceptionHandler.java:54)
	at org.apache.nifi.processor.util.pattern.ExceptionHandler.execute(ExceptionHandler.java:148)
	at org.apache.nifi.processors.standard.PutSQL.lambda$new$5(PutSQL.java:342)
	at org.apache.nifi.processors.standard.PutSQL.lambda$new$7(PutSQL.java:387)
	at org.apache.nifi.processor.util.pattern.PutGroup.putFlowFiles(PutGroup.java:91)
	at org.apache.nifi.processor.util.pattern.Put.onTrigger(Put.java:103)
	at org.apache.nifi.processors.standard.PutSQL.lambda$onTrigger$19(PutSQL.java:635)
	at org.apache.nifi.processor.util.pattern.PartialFunctions.onTrigger(PartialFunctions.java:120)
	at org.apache.nifi.processor.util.pattern.RollbackOnFailure.onTrigger(RollbackOnFailure.java:184)
	at org.apache.nifi.processors.standard.PutSQL.onTrigger(PutSQL.java:635)
	at org.apache.nifi.util.StandardProcessorTestRunner$RunProcessor.call(StandardProcessorTestRunner.java:284)
	at org.apache.nifi.util.StandardProcessorTestRunner$RunProcessor.call(StandardProcessorTestRunner.java:278)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.sql.SQLException: Unit Test Generated SQLException
	at org.apache.nifi.processors.standard.PutSQL$StatementFlowFileEnclosure.getCachedStatement(PutSQL.java:1014)
	at org.apache.nifi.processors.standard.PutSQL.lambda$null$4(PutSQL.java:343)
	at org.apache.nifi.processor.util.pattern.ExceptionHandler.execute(ExceptionHandler.java:127)
	... 16 more
]]></system-err>
  </testcase>
  <testcase name="testFailInMiddleWithBadStatementAndNotSupportTransaction" classname="org.apache.nifi.processors.standard.TestPutSQL" time="0.005">
    <system-err><![CDATA[[pool-5280-thread-1] ERROR org.apache.nifi.processors.standard.PutSQL - PutSQL[id=eb6bee52-6d19-4917-b224-e41cb0a8e1aa] Failed to update database for FlowFile[1,90536395743740.mockFlowFile,22B] due to java.sql.SQLSyntaxErrorException: Syntax error: Encountered "<EOF>" at line 1, column 22.; routing to failure: java.sql.SQLSyntaxErrorException: Syntax error: Encountered "<EOF>" at line 1, column 22.
java.sql.SQLSyntaxErrorException: Syntax error: Encountered "<EOF>" at line 1, column 22.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement42.<init>(Unknown Source)
	at org.apache.derby.jdbc.Driver42.newEmbedPreparedStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.prepareStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.prepareStatement(Unknown Source)
	at org.apache.nifi.processors.standard.PutSQL$StatementFlowFileEnclosure.getCachedStatement(PutSQL.java:1014)
	at org.apache.nifi.processors.standard.PutSQL.lambda$null$4(PutSQL.java:343)
	at org.apache.nifi.processor.util.pattern.ExceptionHandler.execute(ExceptionHandler.java:127)
	at org.apache.nifi.processors.standard.PutSQL.lambda$new$5(PutSQL.java:342)
	at org.apache.nifi.processors.standard.PutSQL.lambda$new$7(PutSQL.java:387)
	at org.apache.nifi.processor.util.pattern.PutGroup.putFlowFiles(PutGroup.java:91)
	at org.apache.nifi.processor.util.pattern.Put.onTrigger(Put.java:103)
	at org.apache.nifi.processors.standard.PutSQL.lambda$onTrigger$19(PutSQL.java:635)
	at org.apache.nifi.processor.util.pattern.PartialFunctions.onTrigger(PartialFunctions.java:120)
	at org.apache.nifi.processor.util.pattern.RollbackOnFailure.onTrigger(RollbackOnFailure.java:184)
	at org.apache.nifi.processors.standard.PutSQL.onTrigger(PutSQL.java:635)
	at org.apache.nifi.util.StandardProcessorTestRunner$RunProcessor.call(StandardProcessorTestRunner.java:284)
	at org.apache.nifi.util.StandardProcessorTestRunner$RunProcessor.call(StandardProcessorTestRunner.java:278)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: ERROR 42X01: Syntax error: Encountered "<EOF>" at line 1, column 22.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.sql.compile.ParserImpl.parseStatementOrSearchCondition(Unknown Source)
	at org.apache.derby.impl.sql.compile.ParserImpl.parseStatement(Unknown Source)
	at org.apache.derby.impl.sql.GenericStatement.prepMinion(Unknown Source)
	at org.apache.derby.impl.sql.GenericStatement.prepare(Unknown Source)
	at org.apache.derby.impl.sql.conn.GenericLanguageConnectionContext.prepareInternalStatement(Unknown Source)
	... 24 more
[pool-5280-thread-1] ERROR org.apache.nifi.processors.standard.PutSQL - PutSQL[id=eb6bee52-6d19-4917-b224-e41cb0a8e1aa] Failed to update database for [] due to java.sql.SQLSyntaxErrorException: Syntax error: Encountered "<EOF>" at line 1, column 22.; routing to failure: java.sql.SQLSyntaxErrorException: Syntax error: Encountered "<EOF>" at line 1, column 22.
java.sql.SQLSyntaxErrorException: Syntax error: Encountered "<EOF>" at line 1, column 22.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement42.<init>(Unknown Source)
	at org.apache.derby.jdbc.Driver42.newEmbedPreparedStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.prepareStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.prepareStatement(Unknown Source)
	at org.apache.nifi.processors.standard.PutSQL$StatementFlowFileEnclosure.getCachedStatement(PutSQL.java:1014)
	at org.apache.nifi.processors.standard.PutSQL.lambda$null$8(PutSQL.java:402)
	at org.apache.nifi.processor.util.pattern.ExceptionHandler.execute(ExceptionHandler.java:127)
	at org.apache.nifi.processors.standard.PutSQL.lambda$new$10(PutSQL.java:401)
	at org.apache.nifi.processor.util.pattern.PutGroup.putFlowFiles(PutGroup.java:94)
	at org.apache.nifi.processor.util.pattern.Put.onTrigger(Put.java:103)
	at org.apache.nifi.processors.standard.PutSQL.lambda$onTrigger$19(PutSQL.java:635)
	at org.apache.nifi.processor.util.pattern.PartialFunctions.onTrigger(PartialFunctions.java:120)
	at org.apache.nifi.processor.util.pattern.RollbackOnFailure.onTrigger(RollbackOnFailure.java:184)
	at org.apache.nifi.processors.standard.PutSQL.onTrigger(PutSQL.java:635)
	at org.apache.nifi.util.StandardProcessorTestRunner$RunProcessor.call(StandardProcessorTestRunner.java:284)
	at org.apache.nifi.util.StandardProcessorTestRunner$RunProcessor.call(StandardProcessorTestRunner.java:278)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: ERROR 42X01: Syntax error: Encountered "<EOF>" at line 1, column 22.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.sql.compile.ParserImpl.parseStatementOrSearchCondition(Unknown Source)
	at org.apache.derby.impl.sql.compile.ParserImpl.parseStatement(Unknown Source)
	at org.apache.derby.impl.sql.GenericStatement.prepMinion(Unknown Source)
	at org.apache.derby.impl.sql.GenericStatement.prepare(Unknown Source)
	at org.apache.derby.impl.sql.conn.GenericLanguageConnectionContext.prepareInternalStatement(Unknown Source)
	... 23 more
]]></system-err>
  </testcase>
  <testcase name="testInsertWithGeneratedKeys" classname="org.apache.nifi.processors.standard.TestPutSQL" time="0.026"/>
  <testcase name="testWithNullParameter" classname="org.apache.nifi.processors.standard.TestPutSQL" time="0.019"/>
  <testcase name="testFailInMiddleWithBadParameterTypeAndSupportTransaction" classname="org.apache.nifi.processors.standard.TestPutSQL" time="0.022">
    <system-err><![CDATA[[pool-5283-thread-1] ERROR org.apache.nifi.processors.standard.PutSQL - PutSQL[id=ce5c5f4c-7580-4d06-90aa-dee20671398b] Failed to update database for FlowFile[1,90536446070036.mockFlowFile,54B] due to java.sql.SQLDataException: Invalid character string format for type INTEGER.; routing to failure: java.sql.SQLDataException: Invalid character string format for type INTEGER.
java.sql.SQLDataException: Invalid character string format for type INTEGER.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedResultSet.noStateChangeException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.setString(Unknown Source)
	at org.apache.nifi.util.db.JdbcCommon.setParameter(JdbcCommon.java:850)
	at org.apache.nifi.util.db.JdbcCommon.setParameters(JdbcCommon.java:696)
	at org.apache.nifi.processors.standard.PutSQL.lambda$null$4(PutSQL.java:344)
	at org.apache.nifi.processor.util.pattern.ExceptionHandler.execute(ExceptionHandler.java:127)
	at org.apache.nifi.processors.standard.PutSQL.lambda$new$5(PutSQL.java:342)
	at org.apache.nifi.processors.standard.PutSQL.lambda$new$7(PutSQL.java:387)
	at org.apache.nifi.processor.util.pattern.PutGroup.putFlowFiles(PutGroup.java:91)
	at org.apache.nifi.processor.util.pattern.Put.onTrigger(Put.java:103)
	at org.apache.nifi.processors.standard.PutSQL.lambda$onTrigger$19(PutSQL.java:635)
	at org.apache.nifi.processor.util.pattern.PartialFunctions.onTrigger(PartialFunctions.java:120)
	at org.apache.nifi.processor.util.pattern.RollbackOnFailure.onTrigger(RollbackOnFailure.java:184)
	at org.apache.nifi.processors.standard.PutSQL.onTrigger(PutSQL.java:635)
	at org.apache.nifi.util.StandardProcessorTestRunner$RunProcessor.call(StandardProcessorTestRunner.java:284)
	at org.apache.nifi.util.StandardProcessorTestRunner$RunProcessor.call(StandardProcessorTestRunner.java:278)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: ERROR 22018: Invalid character string format for type INTEGER.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.iapi.types.DataType.invalidFormat(Unknown Source)
	at org.apache.derby.iapi.types.SQLInteger.setValue(Unknown Source)
	... 21 more
]]></system-err>
  </testcase>
  <testcase name="testFailInMiddleWithBadStatementRollbackOnFailure" classname="org.apache.nifi.processors.standard.TestPutSQL" time="0.002">
    <system-err><![CDATA[[pool-5284-thread-1] DEBUG org.apache.nifi.processors.standard.PutSQL - PutSQL[id=ddfb034a-80d1-410f-b273-4980073f9196] Adjusted InvalidInput to Result{destination=ProcessException, penalty=Yield} based on context rollbackOnFailure=true, processedCount=0, transactional=true
[pool-5284-thread-1] ERROR org.apache.nifi.processors.standard.PutSQL - PutSQL[id=ddfb034a-80d1-410f-b273-4980073f9196] org.apache.nifi.processors.standard.PutSQL$$Lambda$2020/1547646810@57fc3138 failed to process due to org.apache.nifi.processor.exception.ProcessException: Failed to process FlowFile[1,90536468041334.mockFlowFile,22B] due to java.sql.SQLSyntaxErrorException: Syntax error: Encountered "<EOF>" at line 1, column 22.; rolling back session: org.apache.nifi.processor.exception.ProcessException: Failed to process FlowFile[1,90536468041334.mockFlowFile,22B] due to java.sql.SQLSyntaxErrorException: Syntax error: Encountered "<EOF>" at line 1, column 22.
org.apache.nifi.processor.exception.ProcessException: Failed to process FlowFile[1,90536468041334.mockFlowFile,22B] due to java.sql.SQLSyntaxErrorException: Syntax error: Encountered "<EOF>" at line 1, column 22.
	at org.apache.nifi.processor.util.pattern.ExceptionHandler.lambda$createOnGroupError$2(ExceptionHandler.java:226)
	at org.apache.nifi.processor.util.pattern.ExceptionHandler.lambda$createOnError$1(ExceptionHandler.java:179)
	at org.apache.nifi.processor.util.pattern.ExceptionHandler$OnError.lambda$andThen$0(ExceptionHandler.java:54)
	at org.apache.nifi.processor.util.pattern.ExceptionHandler$OnError.lambda$andThen$0(ExceptionHandler.java:54)
	at org.apache.nifi.processor.util.pattern.ExceptionHandler.execute(ExceptionHandler.java:148)
	at org.apache.nifi.processors.standard.PutSQL.lambda$new$5(PutSQL.java:342)
	at org.apache.nifi.processors.standard.PutSQL.lambda$new$7(PutSQL.java:387)
	at org.apache.nifi.processor.util.pattern.PutGroup.putFlowFiles(PutGroup.java:91)
	at org.apache.nifi.processor.util.pattern.Put.onTrigger(Put.java:103)
	at org.apache.nifi.processors.standard.PutSQL.lambda$onTrigger$19(PutSQL.java:635)
	at org.apache.nifi.processor.util.pattern.PartialFunctions.onTrigger(PartialFunctions.java:120)
	at org.apache.nifi.processor.util.pattern.RollbackOnFailure.onTrigger(RollbackOnFailure.java:184)
	at org.apache.nifi.processors.standard.PutSQL.onTrigger(PutSQL.java:635)
	at org.apache.nifi.util.StandardProcessorTestRunner$RunProcessor.call(StandardProcessorTestRunner.java:284)
	at org.apache.nifi.util.StandardProcessorTestRunner$RunProcessor.call(StandardProcessorTestRunner.java:278)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.sql.SQLSyntaxErrorException: Syntax error: Encountered "<EOF>" at line 1, column 22.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement42.<init>(Unknown Source)
	at org.apache.derby.jdbc.Driver42.newEmbedPreparedStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.prepareStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.prepareStatement(Unknown Source)
	at org.apache.nifi.processors.standard.PutSQL$StatementFlowFileEnclosure.getCachedStatement(PutSQL.java:1014)
	at org.apache.nifi.processors.standard.PutSQL.lambda$null$4(PutSQL.java:343)
	at org.apache.nifi.processor.util.pattern.ExceptionHandler.execute(ExceptionHandler.java:127)
	... 16 more
Caused by: ERROR 42X01: Syntax error: Encountered "<EOF>" at line 1, column 22.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.sql.compile.ParserImpl.parseStatementOrSearchCondition(Unknown Source)
	at org.apache.derby.impl.sql.compile.ParserImpl.parseStatement(Unknown Source)
	at org.apache.derby.impl.sql.GenericStatement.prepMinion(Unknown Source)
	at org.apache.derby.impl.sql.GenericStatement.prepare(Unknown Source)
	at org.apache.derby.impl.sql.conn.GenericLanguageConnectionContext.prepareInternalStatement(Unknown Source)
	... 24 more
[pool-5284-thread-1] WARN org.apache.nifi.processors.standard.PutSQL - PutSQL[id=ddfb034a-80d1-410f-b273-4980073f9196] Administratively yielding org.apache.nifi.processors.standard.PutSQL after rolling back due to org.apache.nifi.processor.exception.ProcessException: Failed to process FlowFile[1,90536468041334.mockFlowFile,22B] due to java.sql.SQLSyntaxErrorException: Syntax error: Encountered "<EOF>" at line 1, column 22.: org.apache.nifi.processor.exception.ProcessException: Failed to process FlowFile[1,90536468041334.mockFlowFile,22B] due to java.sql.SQLSyntaxErrorException: Syntax error: Encountered "<EOF>" at line 1, column 22.
[pool-5284-thread-1] WARN org.apache.nifi.processors.standard.PutSQL - 
org.apache.nifi.processor.exception.ProcessException: Failed to process FlowFile[1,90536468041334.mockFlowFile,22B] due to java.sql.SQLSyntaxErrorException: Syntax error: Encountered "<EOF>" at line 1, column 22.
	at org.apache.nifi.processor.util.pattern.ExceptionHandler.lambda$createOnGroupError$2(ExceptionHandler.java:226)
	at org.apache.nifi.processor.util.pattern.ExceptionHandler.lambda$createOnError$1(ExceptionHandler.java:179)
	at org.apache.nifi.processor.util.pattern.ExceptionHandler$OnError.lambda$andThen$0(ExceptionHandler.java:54)
	at org.apache.nifi.processor.util.pattern.ExceptionHandler$OnError.lambda$andThen$0(ExceptionHandler.java:54)
	at org.apache.nifi.processor.util.pattern.ExceptionHandler.execute(ExceptionHandler.java:148)
	at org.apache.nifi.processors.standard.PutSQL.lambda$new$5(PutSQL.java:342)
	at org.apache.nifi.processors.standard.PutSQL.lambda$new$7(PutSQL.java:387)
	at org.apache.nifi.processor.util.pattern.PutGroup.putFlowFiles(PutGroup.java:91)
	at org.apache.nifi.processor.util.pattern.Put.onTrigger(Put.java:103)
	at org.apache.nifi.processors.standard.PutSQL.lambda$onTrigger$19(PutSQL.java:635)
	at org.apache.nifi.processor.util.pattern.PartialFunctions.onTrigger(PartialFunctions.java:120)
	at org.apache.nifi.processor.util.pattern.RollbackOnFailure.onTrigger(RollbackOnFailure.java:184)
	at org.apache.nifi.processors.standard.PutSQL.onTrigger(PutSQL.java:635)
	at org.apache.nifi.util.StandardProcessorTestRunner$RunProcessor.call(StandardProcessorTestRunner.java:284)
	at org.apache.nifi.util.StandardProcessorTestRunner$RunProcessor.call(StandardProcessorTestRunner.java:278)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.sql.SQLSyntaxErrorException: Syntax error: Encountered "<EOF>" at line 1, column 22.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement42.<init>(Unknown Source)
	at org.apache.derby.jdbc.Driver42.newEmbedPreparedStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.prepareStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.prepareStatement(Unknown Source)
	at org.apache.nifi.processors.standard.PutSQL$StatementFlowFileEnclosure.getCachedStatement(PutSQL.java:1014)
	at org.apache.nifi.processors.standard.PutSQL.lambda$null$4(PutSQL.java:343)
	at org.apache.nifi.processor.util.pattern.ExceptionHandler.execute(ExceptionHandler.java:127)
	... 16 more
Caused by: ERROR 42X01: Syntax error: Encountered "<EOF>" at line 1, column 22.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.sql.compile.ParserImpl.parseStatementOrSearchCondition(Unknown Source)
	at org.apache.derby.impl.sql.compile.ParserImpl.parseStatement(Unknown Source)
	at org.apache.derby.impl.sql.GenericStatement.prepMinion(Unknown Source)
	at org.apache.derby.impl.sql.GenericStatement.prepare(Unknown Source)
	at org.apache.derby.impl.sql.conn.GenericLanguageConnectionContext.prepareInternalStatement(Unknown Source)
	... 24 more
]]></system-err>
  </testcase>
  <testcase name="testUsingTimeValuesEpochAndString" classname="org.apache.nifi.processors.standard.TestPutSQL" time="0.016"/>
  <testcase name="testProvenanceEventsWithBatchMode" classname="org.apache.nifi.processors.standard.TestPutSQL" time="0.025"/>
  <testcase name="testNullFragmentCountRollbackOnFailure" classname="org.apache.nifi.processors.standard.TestPutSQL" time="0.002">
    <system-err><![CDATA[[pool-5287-thread-1] DEBUG org.apache.nifi.processors.standard.PutSQL - PutSQL[id=9ba748c2-9d8f-4e99-ac2c-c095af010240] Adjusted InvalidInput to Result{destination=ProcessException, penalty=Yield} based on context rollbackOnFailure=true, processedCount=0, transactional=true
[pool-5287-thread-1] ERROR org.apache.nifi.processors.standard.PutSQL - PutSQL[id=9ba748c2-9d8f-4e99-ac2c-c095af010240] org.apache.nifi.processors.standard.PutSQL$$Lambda$2020/1547646810@2bf5ba54 failed to process due to org.apache.nifi.processor.exception.ProcessException: Failed to process 2 FlowFiles including FlowFile[0,90536510846299.mockFlowFile,0B] due to java.lang.IllegalArgumentException: Cannot process FlowFile[1,90536510857470.mockFlowFile,0B] because there are 2 FlowFiles with the same fragment.identifier attribute but not all FlowFiles have a fragment.count attribute; rolling back session: org.apache.nifi.processor.exception.ProcessException: Failed to process 2 FlowFiles including FlowFile[0,90536510846299.mockFlowFile,0B] due to java.lang.IllegalArgumentException: Cannot process FlowFile[1,90536510857470.mockFlowFile,0B] because there are 2 FlowFiles with the same fragment.identifier attribute but not all FlowFiles have a fragment.count attribute
org.apache.nifi.processor.exception.ProcessException: Failed to process 2 FlowFiles including FlowFile[0,90536510846299.mockFlowFile,0B] due to java.lang.IllegalArgumentException: Cannot process FlowFile[1,90536510857470.mockFlowFile,0B] because there are 2 FlowFiles with the same fragment.identifier attribute but not all FlowFiles have a fragment.count attribute
	at org.apache.nifi.processor.util.pattern.ExceptionHandler.lambda$createOnGroupError$2(ExceptionHandler.java:226)
	at org.apache.nifi.processors.standard.PutSQL.pollFlowFiles(PutSQL.java:690)
	at org.apache.nifi.processors.standard.PutSQL.lambda$new$0(PutSQL.java:275)
	at org.apache.nifi.processor.util.pattern.Put.onTrigger(Put.java:86)
	at org.apache.nifi.processors.standard.PutSQL.lambda$onTrigger$19(PutSQL.java:635)
	at org.apache.nifi.processor.util.pattern.PartialFunctions.onTrigger(PartialFunctions.java:120)
	at org.apache.nifi.processor.util.pattern.RollbackOnFailure.onTrigger(RollbackOnFailure.java:184)
	at org.apache.nifi.processors.standard.PutSQL.onTrigger(PutSQL.java:635)
	at org.apache.nifi.util.StandardProcessorTestRunner$RunProcessor.call(StandardProcessorTestRunner.java:284)
	at org.apache.nifi.util.StandardProcessorTestRunner$RunProcessor.call(StandardProcessorTestRunner.java:278)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.IllegalArgumentException: Cannot process FlowFile[1,90536510857470.mockFlowFile,0B] because there are 2 FlowFiles with the same fragment.identifier attribute but not all FlowFiles have a fragment.count attribute
	at org.apache.nifi.processors.standard.PutSQL.lambda$isFragmentedTransactionReady$23(PutSQL.java:761)
	at org.apache.nifi.processors.standard.PutSQL.isFragmentedTransactionReady(PutSQL.java:768)
	at org.apache.nifi.processors.standard.PutSQL.pollFlowFiles(PutSQL.java:680)
	... 14 more
[pool-5287-thread-1] WARN org.apache.nifi.processors.standard.PutSQL - PutSQL[id=9ba748c2-9d8f-4e99-ac2c-c095af010240] Administratively yielding org.apache.nifi.processors.standard.PutSQL after rolling back due to org.apache.nifi.processor.exception.ProcessException: Failed to process 2 FlowFiles including FlowFile[0,90536510846299.mockFlowFile,0B] due to java.lang.IllegalArgumentException: Cannot process FlowFile[1,90536510857470.mockFlowFile,0B] because there are 2 FlowFiles with the same fragment.identifier attribute but not all FlowFiles have a fragment.count attribute: org.apache.nifi.processor.exception.ProcessException: Failed to process 2 FlowFiles including FlowFile[0,90536510846299.mockFlowFile,0B] due to java.lang.IllegalArgumentException: Cannot process FlowFile[1,90536510857470.mockFlowFile,0B] because there are 2 FlowFiles with the same fragment.identifier attribute but not all FlowFiles have a fragment.count attribute
[pool-5287-thread-1] WARN org.apache.nifi.processors.standard.PutSQL - 
org.apache.nifi.processor.exception.ProcessException: Failed to process 2 FlowFiles including FlowFile[0,90536510846299.mockFlowFile,0B] due to java.lang.IllegalArgumentException: Cannot process FlowFile[1,90536510857470.mockFlowFile,0B] because there are 2 FlowFiles with the same fragment.identifier attribute but not all FlowFiles have a fragment.count attribute
	at org.apache.nifi.processor.util.pattern.ExceptionHandler.lambda$createOnGroupError$2(ExceptionHandler.java:226)
	at org.apache.nifi.processors.standard.PutSQL.pollFlowFiles(PutSQL.java:690)
	at org.apache.nifi.processors.standard.PutSQL.lambda$new$0(PutSQL.java:275)
	at org.apache.nifi.processor.util.pattern.Put.onTrigger(Put.java:86)
	at org.apache.nifi.processors.standard.PutSQL.lambda$onTrigger$19(PutSQL.java:635)
	at org.apache.nifi.processor.util.pattern.PartialFunctions.onTrigger(PartialFunctions.java:120)
	at org.apache.nifi.processor.util.pattern.RollbackOnFailure.onTrigger(RollbackOnFailure.java:184)
	at org.apache.nifi.processors.standard.PutSQL.onTrigger(PutSQL.java:635)
	at org.apache.nifi.util.StandardProcessorTestRunner$RunProcessor.call(StandardProcessorTestRunner.java:284)
	at org.apache.nifi.util.StandardProcessorTestRunner$RunProcessor.call(StandardProcessorTestRunner.java:278)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.IllegalArgumentException: Cannot process FlowFile[1,90536510857470.mockFlowFile,0B] because there are 2 FlowFiles with the same fragment.identifier attribute but not all FlowFiles have a fragment.count attribute
	at org.apache.nifi.processors.standard.PutSQL.lambda$isFragmentedTransactionReady$23(PutSQL.java:761)
	at org.apache.nifi.processors.standard.PutSQL.isFragmentedTransactionReady(PutSQL.java:768)
	at org.apache.nifi.processors.standard.PutSQL.pollFlowFiles(PutSQL.java:680)
	... 14 more
]]></system-err>
  </testcase>
  <testcase name="testInvalidStatement" classname="org.apache.nifi.processors.standard.TestPutSQL" time="0.022">
    <system-err><![CDATA[[pool-5288-thread-1] ERROR org.apache.nifi.processors.standard.PutSQL - PutSQL[id=ea312490-b2fe-4c61-a4f3-0f53855f1ed4] Failed to update database for FlowFile[0,90536530022172.mockFlowFile,106B] due to java.sql.SQLSyntaxErrorException: Syntax error: Encountered ";" at line 1, column 54.; routing to failure: java.sql.SQLSyntaxErrorException: Syntax error: Encountered ";" at line 1, column 54.
java.sql.SQLSyntaxErrorException: Syntax error: Encountered ";" at line 1, column 54.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement42.<init>(Unknown Source)
	at org.apache.derby.jdbc.Driver42.newEmbedPreparedStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.prepareStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.prepareStatement(Unknown Source)
	at org.apache.nifi.processors.standard.PutSQL$StatementFlowFileEnclosure.getCachedStatement(PutSQL.java:1014)
	at org.apache.nifi.processors.standard.PutSQL.lambda$null$4(PutSQL.java:343)
	at org.apache.nifi.processor.util.pattern.ExceptionHandler.execute(ExceptionHandler.java:127)
	at org.apache.nifi.processors.standard.PutSQL.lambda$new$5(PutSQL.java:342)
	at org.apache.nifi.processors.standard.PutSQL.lambda$new$7(PutSQL.java:387)
	at org.apache.nifi.processor.util.pattern.PutGroup.putFlowFiles(PutGroup.java:91)
	at org.apache.nifi.processor.util.pattern.Put.onTrigger(Put.java:103)
	at org.apache.nifi.processors.standard.PutSQL.lambda$onTrigger$19(PutSQL.java:635)
	at org.apache.nifi.processor.util.pattern.PartialFunctions.onTrigger(PartialFunctions.java:120)
	at org.apache.nifi.processor.util.pattern.RollbackOnFailure.onTrigger(RollbackOnFailure.java:184)
	at org.apache.nifi.processors.standard.PutSQL.onTrigger(PutSQL.java:635)
	at org.apache.nifi.util.StandardProcessorTestRunner$RunProcessor.call(StandardProcessorTestRunner.java:284)
	at org.apache.nifi.util.StandardProcessorTestRunner$RunProcessor.call(StandardProcessorTestRunner.java:278)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: ERROR 42X01: Syntax error: Encountered ";" at line 1, column 54.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.sql.compile.ParserImpl.parseStatementOrSearchCondition(Unknown Source)
	at org.apache.derby.impl.sql.compile.ParserImpl.parseStatement(Unknown Source)
	at org.apache.derby.impl.sql.GenericStatement.prepMinion(Unknown Source)
	at org.apache.derby.impl.sql.GenericStatement.prepare(Unknown Source)
	at org.apache.derby.impl.sql.conn.GenericLanguageConnectionContext.prepareInternalStatement(Unknown Source)
	... 24 more
[pool-5288-thread-1] ERROR org.apache.nifi.processors.standard.PutSQL - PutSQL[id=ea312490-b2fe-4c61-a4f3-0f53855f1ed4] Failed to update database for [] due to java.sql.SQLSyntaxErrorException: Syntax error: Encountered ";" at line 1, column 54.; routing to failure: java.sql.SQLSyntaxErrorException: Syntax error: Encountered ";" at line 1, column 54.
java.sql.SQLSyntaxErrorException: Syntax error: Encountered ";" at line 1, column 54.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement42.<init>(Unknown Source)
	at org.apache.derby.jdbc.Driver42.newEmbedPreparedStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.prepareStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.prepareStatement(Unknown Source)
	at org.apache.nifi.processors.standard.PutSQL$StatementFlowFileEnclosure.getCachedStatement(PutSQL.java:1014)
	at org.apache.nifi.processors.standard.PutSQL.lambda$null$8(PutSQL.java:402)
	at org.apache.nifi.processor.util.pattern.ExceptionHandler.execute(ExceptionHandler.java:127)
	at org.apache.nifi.processors.standard.PutSQL.lambda$new$10(PutSQL.java:401)
	at org.apache.nifi.processor.util.pattern.PutGroup.putFlowFiles(PutGroup.java:94)
	at org.apache.nifi.processor.util.pattern.Put.onTrigger(Put.java:103)
	at org.apache.nifi.processors.standard.PutSQL.lambda$onTrigger$19(PutSQL.java:635)
	at org.apache.nifi.processor.util.pattern.PartialFunctions.onTrigger(PartialFunctions.java:120)
	at org.apache.nifi.processor.util.pattern.RollbackOnFailure.onTrigger(RollbackOnFailure.java:184)
	at org.apache.nifi.processors.standard.PutSQL.onTrigger(PutSQL.java:635)
	at org.apache.nifi.util.StandardProcessorTestRunner$RunProcessor.call(StandardProcessorTestRunner.java:284)
	at org.apache.nifi.util.StandardProcessorTestRunner$RunProcessor.call(StandardProcessorTestRunner.java:278)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: ERROR 42X01: Syntax error: Encountered ";" at line 1, column 54.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.sql.compile.ParserImpl.parseStatementOrSearchCondition(Unknown Source)
	at org.apache.derby.impl.sql.compile.ParserImpl.parseStatement(Unknown Source)
	at org.apache.derby.impl.sql.GenericStatement.prepMinion(Unknown Source)
	at org.apache.derby.impl.sql.GenericStatement.prepare(Unknown Source)
	at org.apache.derby.impl.sql.conn.GenericLanguageConnectionContext.prepareInternalStatement(Unknown Source)
	... 23 more
]]></system-err>
  </testcase>
  <testcase name="testBinaryColumnTypes" classname="org.apache.nifi.processors.standard.TestPutSQL" time="0.055"/>
  <testcase name="testMultipleFlowFilesSuccessfulInTransaction" classname="org.apache.nifi.processors.standard.TestPutSQL" time="0.03">
    <system-err><![CDATA[[pool-5290-thread-1] DEBUG org.apache.nifi.processors.standard.PutSQL - PutSQL[id=2ffc1485-5ab4-443d-9d49-2717850a13e9] Not enough FlowFiles for transaction. Returning all FlowFiles to queue
[pool-5290-thread-1] DEBUG org.apache.nifi.processors.standard.PutSQL - PutSQL[id=2ffc1485-5ab4-443d-9d49-2717850a13e9] No incoming FlowFiles.
]]></system-err>
  </testcase>
  <testcase name="testTransactionTimeoutRollbackOnFailure" classname="org.apache.nifi.processors.standard.TestPutSQL" time="0.002">
    <system-err><![CDATA[[pool-5292-thread-1] DEBUG org.apache.nifi.processors.standard.PutSQL - PutSQL[id=048f531a-c734-453f-853a-0df5e08d4c11] Adjusted InvalidInput to Result{destination=ProcessException, penalty=Yield} based on context rollbackOnFailure=true, processedCount=0, transactional=true
[pool-5292-thread-1] ERROR org.apache.nifi.processors.standard.PutSQL - PutSQL[id=048f531a-c734-453f-853a-0df5e08d4c11] org.apache.nifi.processors.standard.PutSQL$$Lambda$2020/1547646810@5f74aa62 failed to process due to org.apache.nifi.processor.exception.ProcessException: Failed to process FlowFile[0,null,0B] due to java.lang.IllegalArgumentException: The transaction timeout has expired for the following FlowFiles; they will be routed to failure: [FlowFile[0,null,0B]]; rolling back session: org.apache.nifi.processor.exception.ProcessException: Failed to process FlowFile[0,null,0B] due to java.lang.IllegalArgumentException: The transaction timeout has expired for the following FlowFiles; they will be routed to failure: [FlowFile[0,null,0B]]
org.apache.nifi.processor.exception.ProcessException: Failed to process FlowFile[0,null,0B] due to java.lang.IllegalArgumentException: The transaction timeout has expired for the following FlowFiles; they will be routed to failure: [FlowFile[0,null,0B]]
	at org.apache.nifi.processor.util.pattern.ExceptionHandler.lambda$createOnGroupError$2(ExceptionHandler.java:226)
	at org.apache.nifi.processors.standard.PutSQL.pollFlowFiles(PutSQL.java:690)
	at org.apache.nifi.processors.standard.PutSQL.lambda$new$0(PutSQL.java:275)
	at org.apache.nifi.processor.util.pattern.Put.onTrigger(Put.java:86)
	at org.apache.nifi.processors.standard.PutSQL.lambda$onTrigger$19(PutSQL.java:635)
	at org.apache.nifi.processor.util.pattern.PartialFunctions.onTrigger(PartialFunctions.java:120)
	at org.apache.nifi.processor.util.pattern.RollbackOnFailure.onTrigger(RollbackOnFailure.java:184)
	at org.apache.nifi.processors.standard.PutSQL.onTrigger(PutSQL.java:635)
	at org.apache.nifi.util.StandardProcessorTestRunner$RunProcessor.call(StandardProcessorTestRunner.java:284)
	at org.apache.nifi.util.StandardProcessorTestRunner$RunProcessor.call(StandardProcessorTestRunner.java:278)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.IllegalArgumentException: The transaction timeout has expired for the following FlowFiles; they will be routed to failure: [FlowFile[0,null,0B]]
	at org.apache.nifi.processors.standard.PutSQL.lambda$isFragmentedTransactionReady$23(PutSQL.java:761)
	at org.apache.nifi.processors.standard.PutSQL.isFragmentedTransactionReady(PutSQL.java:831)
	at org.apache.nifi.processors.standard.PutSQL.pollFlowFiles(PutSQL.java:680)
	... 14 more
[pool-5292-thread-1] WARN org.apache.nifi.processors.standard.PutSQL - PutSQL[id=048f531a-c734-453f-853a-0df5e08d4c11] Administratively yielding org.apache.nifi.processors.standard.PutSQL after rolling back due to org.apache.nifi.processor.exception.ProcessException: Failed to process FlowFile[0,null,0B] due to java.lang.IllegalArgumentException: The transaction timeout has expired for the following FlowFiles; they will be routed to failure: [FlowFile[0,null,0B]]: org.apache.nifi.processor.exception.ProcessException: Failed to process FlowFile[0,null,0B] due to java.lang.IllegalArgumentException: The transaction timeout has expired for the following FlowFiles; they will be routed to failure: [FlowFile[0,null,0B]]
[pool-5292-thread-1] WARN org.apache.nifi.processors.standard.PutSQL - 
org.apache.nifi.processor.exception.ProcessException: Failed to process FlowFile[0,null,0B] due to java.lang.IllegalArgumentException: The transaction timeout has expired for the following FlowFiles; they will be routed to failure: [FlowFile[0,null,0B]]
	at org.apache.nifi.processor.util.pattern.ExceptionHandler.lambda$createOnGroupError$2(ExceptionHandler.java:226)
	at org.apache.nifi.processors.standard.PutSQL.pollFlowFiles(PutSQL.java:690)
	at org.apache.nifi.processors.standard.PutSQL.lambda$new$0(PutSQL.java:275)
	at org.apache.nifi.processor.util.pattern.Put.onTrigger(Put.java:86)
	at org.apache.nifi.processors.standard.PutSQL.lambda$onTrigger$19(PutSQL.java:635)
	at org.apache.nifi.processor.util.pattern.PartialFunctions.onTrigger(PartialFunctions.java:120)
	at org.apache.nifi.processor.util.pattern.RollbackOnFailure.onTrigger(RollbackOnFailure.java:184)
	at org.apache.nifi.processors.standard.PutSQL.onTrigger(PutSQL.java:635)
	at org.apache.nifi.util.StandardProcessorTestRunner$RunProcessor.call(StandardProcessorTestRunner.java:284)
	at org.apache.nifi.util.StandardProcessorTestRunner$RunProcessor.call(StandardProcessorTestRunner.java:278)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.IllegalArgumentException: The transaction timeout has expired for the following FlowFiles; they will be routed to failure: [FlowFile[0,null,0B]]
	at org.apache.nifi.processors.standard.PutSQL.lambda$isFragmentedTransactionReady$23(PutSQL.java:761)
	at org.apache.nifi.processors.standard.PutSQL.isFragmentedTransactionReady(PutSQL.java:831)
	at org.apache.nifi.processors.standard.PutSQL.pollFlowFiles(PutSQL.java:680)
	... 14 more
]]></system-err>
  </testcase>
  <testcase name="testTransactionTimeout" classname="org.apache.nifi.processors.standard.TestPutSQL" time="0.001">
    <system-err><![CDATA[[pool-5293-thread-1] DEBUG org.apache.nifi.processors.standard.PutSQL - PutSQL[id=221cdfca-cf2c-403f-8950-ac46cbc26394] No incoming FlowFiles.
]]></system-err>
  </testcase>
  <testcase name="testProvenanceEventsWithObtainGeneratedKeys" classname="org.apache.nifi.processors.standard.TestPutSQL" time="0.027"/>
  <testcase name="testMultipleStatementsWithinFlowFileRollbackOnFailure" classname="org.apache.nifi.processors.standard.TestPutSQL" time="0.026">
    <system-err><![CDATA[[pool-5295-thread-1] DEBUG org.apache.nifi.processors.standard.PutSQL - PutSQL[id=73ad8b40-8555-4ce8-9cd7-96dbda90c55a] Adjusted InvalidInput to Result{destination=ProcessException, penalty=Yield} based on context rollbackOnFailure=true, processedCount=0, transactional=true
[pool-5295-thread-1] ERROR org.apache.nifi.processors.standard.PutSQL - PutSQL[id=73ad8b40-8555-4ce8-9cd7-96dbda90c55a] org.apache.nifi.processors.standard.PutSQL$$Lambda$2020/1547646810@6879542d failed to process due to org.apache.nifi.processor.exception.ProcessException: Failed to process FlowFile[0,90536667245348.mockFlowFile,100B] due to java.sql.SQLSyntaxErrorException: Syntax error: Encountered ";" at line 1, column 54.; rolling back session: org.apache.nifi.processor.exception.ProcessException: Failed to process FlowFile[0,90536667245348.mockFlowFile,100B] due to java.sql.SQLSyntaxErrorException: Syntax error: Encountered ";" at line 1, column 54.
org.apache.nifi.processor.exception.ProcessException: Failed to process FlowFile[0,90536667245348.mockFlowFile,100B] due to java.sql.SQLSyntaxErrorException: Syntax error: Encountered ";" at line 1, column 54.
	at org.apache.nifi.processor.util.pattern.ExceptionHandler.lambda$createOnGroupError$2(ExceptionHandler.java:226)
	at org.apache.nifi.processor.util.pattern.ExceptionHandler.lambda$createOnError$1(ExceptionHandler.java:179)
	at org.apache.nifi.processor.util.pattern.ExceptionHandler$OnError.lambda$andThen$0(ExceptionHandler.java:54)
	at org.apache.nifi.processor.util.pattern.ExceptionHandler$OnError.lambda$andThen$0(ExceptionHandler.java:54)
	at org.apache.nifi.processor.util.pattern.ExceptionHandler.execute(ExceptionHandler.java:148)
	at org.apache.nifi.processors.standard.PutSQL.lambda$new$5(PutSQL.java:342)
	at org.apache.nifi.processors.standard.PutSQL.lambda$new$7(PutSQL.java:387)
	at org.apache.nifi.processor.util.pattern.PutGroup.putFlowFiles(PutGroup.java:91)
	at org.apache.nifi.processor.util.pattern.Put.onTrigger(Put.java:103)
	at org.apache.nifi.processors.standard.PutSQL.lambda$onTrigger$19(PutSQL.java:635)
	at org.apache.nifi.processor.util.pattern.PartialFunctions.onTrigger(PartialFunctions.java:120)
	at org.apache.nifi.processor.util.pattern.RollbackOnFailure.onTrigger(RollbackOnFailure.java:184)
	at org.apache.nifi.processors.standard.PutSQL.onTrigger(PutSQL.java:635)
	at org.apache.nifi.util.StandardProcessorTestRunner$RunProcessor.call(StandardProcessorTestRunner.java:284)
	at org.apache.nifi.util.StandardProcessorTestRunner$RunProcessor.call(StandardProcessorTestRunner.java:278)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.sql.SQLSyntaxErrorException: Syntax error: Encountered ";" at line 1, column 54.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement42.<init>(Unknown Source)
	at org.apache.derby.jdbc.Driver42.newEmbedPreparedStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.prepareStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.prepareStatement(Unknown Source)
	at org.apache.nifi.processors.standard.PutSQL$StatementFlowFileEnclosure.getCachedStatement(PutSQL.java:1014)
	at org.apache.nifi.processors.standard.PutSQL.lambda$null$4(PutSQL.java:343)
	at org.apache.nifi.processor.util.pattern.ExceptionHandler.execute(ExceptionHandler.java:127)
	... 16 more
Caused by: ERROR 42X01: Syntax error: Encountered ";" at line 1, column 54.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.sql.compile.ParserImpl.parseStatementOrSearchCondition(Unknown Source)
	at org.apache.derby.impl.sql.compile.ParserImpl.parseStatement(Unknown Source)
	at org.apache.derby.impl.sql.GenericStatement.prepMinion(Unknown Source)
	at org.apache.derby.impl.sql.GenericStatement.prepare(Unknown Source)
	at org.apache.derby.impl.sql.conn.GenericLanguageConnectionContext.prepareInternalStatement(Unknown Source)
	... 24 more
[pool-5295-thread-1] WARN org.apache.nifi.processors.standard.PutSQL - PutSQL[id=73ad8b40-8555-4ce8-9cd7-96dbda90c55a] Administratively yielding org.apache.nifi.processors.standard.PutSQL after rolling back due to org.apache.nifi.processor.exception.ProcessException: Failed to process FlowFile[0,90536667245348.mockFlowFile,100B] due to java.sql.SQLSyntaxErrorException: Syntax error: Encountered ";" at line 1, column 54.: org.apache.nifi.processor.exception.ProcessException: Failed to process FlowFile[0,90536667245348.mockFlowFile,100B] due to java.sql.SQLSyntaxErrorException: Syntax error: Encountered ";" at line 1, column 54.
[pool-5295-thread-1] WARN org.apache.nifi.processors.standard.PutSQL - 
org.apache.nifi.processor.exception.ProcessException: Failed to process FlowFile[0,90536667245348.mockFlowFile,100B] due to java.sql.SQLSyntaxErrorException: Syntax error: Encountered ";" at line 1, column 54.
	at org.apache.nifi.processor.util.pattern.ExceptionHandler.lambda$createOnGroupError$2(ExceptionHandler.java:226)
	at org.apache.nifi.processor.util.pattern.ExceptionHandler.lambda$createOnError$1(ExceptionHandler.java:179)
	at org.apache.nifi.processor.util.pattern.ExceptionHandler$OnError.lambda$andThen$0(ExceptionHandler.java:54)
	at org.apache.nifi.processor.util.pattern.ExceptionHandler$OnError.lambda$andThen$0(ExceptionHandler.java:54)
	at org.apache.nifi.processor.util.pattern.ExceptionHandler.execute(ExceptionHandler.java:148)
	at org.apache.nifi.processors.standard.PutSQL.lambda$new$5(PutSQL.java:342)
	at org.apache.nifi.processors.standard.PutSQL.lambda$new$7(PutSQL.java:387)
	at org.apache.nifi.processor.util.pattern.PutGroup.putFlowFiles(PutGroup.java:91)
	at org.apache.nifi.processor.util.pattern.Put.onTrigger(Put.java:103)
	at org.apache.nifi.processors.standard.PutSQL.lambda$onTrigger$19(PutSQL.java:635)
	at org.apache.nifi.processor.util.pattern.PartialFunctions.onTrigger(PartialFunctions.java:120)
	at org.apache.nifi.processor.util.pattern.RollbackOnFailure.onTrigger(RollbackOnFailure.java:184)
	at org.apache.nifi.processors.standard.PutSQL.onTrigger(PutSQL.java:635)
	at org.apache.nifi.util.StandardProcessorTestRunner$RunProcessor.call(StandardProcessorTestRunner.java:284)
	at org.apache.nifi.util.StandardProcessorTestRunner$RunProcessor.call(StandardProcessorTestRunner.java:278)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.sql.SQLSyntaxErrorException: Syntax error: Encountered ";" at line 1, column 54.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.<init>(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement42.<init>(Unknown Source)
	at org.apache.derby.jdbc.Driver42.newEmbedPreparedStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.prepareStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.prepareStatement(Unknown Source)
	at org.apache.nifi.processors.standard.PutSQL$StatementFlowFileEnclosure.getCachedStatement(PutSQL.java:1014)
	at org.apache.nifi.processors.standard.PutSQL.lambda$null$4(PutSQL.java:343)
	at org.apache.nifi.processor.util.pattern.ExceptionHandler.execute(ExceptionHandler.java:127)
	... 16 more
Caused by: ERROR 42X01: Syntax error: Encountered ";" at line 1, column 54.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.impl.sql.compile.ParserImpl.parseStatementOrSearchCondition(Unknown Source)
	at org.apache.derby.impl.sql.compile.ParserImpl.parseStatement(Unknown Source)
	at org.apache.derby.impl.sql.GenericStatement.prepMinion(Unknown Source)
	at org.apache.derby.impl.sql.GenericStatement.prepare(Unknown Source)
	at org.apache.derby.impl.sql.conn.GenericLanguageConnectionContext.prepareInternalStatement(Unknown Source)
	... 24 more
]]></system-err>
  </testcase>
  <testcase name="testCommitOnCleanup" classname="org.apache.nifi.processors.standard.TestPutSQL" time="0.03"/>
  <testcase name="testDirectStatements" classname="org.apache.nifi.processors.standard.TestPutSQL" time="0.028"/>
  <testcase name="testKeepFlowFileOrderingWithObtainGeneratedKeys" classname="org.apache.nifi.processors.standard.TestPutSQL" time="0.025"/>
  <testcase name="testFailInMiddleWithBadParameterTypeAndNotSupportTransaction" classname="org.apache.nifi.processors.standard.TestPutSQL" time="0.003">
    <system-err><![CDATA[[pool-5300-thread-1] ERROR org.apache.nifi.processors.standard.PutSQL - PutSQL[id=3d264d30-fda3-49ad-a3e4-7658dfbbbdba] Failed to update database for FlowFile[1,90536758764005.mockFlowFile,54B] due to java.sql.SQLDataException: Invalid character string format for type INTEGER.; routing to failure: java.sql.SQLDataException: Invalid character string format for type INTEGER.
java.sql.SQLDataException: Invalid character string format for type INTEGER.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedResultSet.noStateChangeException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.setString(Unknown Source)
	at org.apache.nifi.util.db.JdbcCommon.setParameter(JdbcCommon.java:850)
	at org.apache.nifi.util.db.JdbcCommon.setParameters(JdbcCommon.java:696)
	at org.apache.nifi.processors.standard.PutSQL.lambda$null$4(PutSQL.java:344)
	at org.apache.nifi.processor.util.pattern.ExceptionHandler.execute(ExceptionHandler.java:127)
	at org.apache.nifi.processors.standard.PutSQL.lambda$new$5(PutSQL.java:342)
	at org.apache.nifi.processors.standard.PutSQL.lambda$new$7(PutSQL.java:387)
	at org.apache.nifi.processor.util.pattern.PutGroup.putFlowFiles(PutGroup.java:91)
	at org.apache.nifi.processor.util.pattern.Put.onTrigger(Put.java:103)
	at org.apache.nifi.processors.standard.PutSQL.lambda$onTrigger$19(PutSQL.java:635)
	at org.apache.nifi.processor.util.pattern.PartialFunctions.onTrigger(PartialFunctions.java:120)
	at org.apache.nifi.processor.util.pattern.RollbackOnFailure.onTrigger(RollbackOnFailure.java:184)
	at org.apache.nifi.processors.standard.PutSQL.onTrigger(PutSQL.java:635)
	at org.apache.nifi.util.StandardProcessorTestRunner$RunProcessor.call(StandardProcessorTestRunner.java:284)
	at org.apache.nifi.util.StandardProcessorTestRunner$RunProcessor.call(StandardProcessorTestRunner.java:278)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: ERROR 22018: Invalid character string format for type INTEGER.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.iapi.types.DataType.invalidFormat(Unknown Source)
	at org.apache.derby.iapi.types.SQLInteger.setValue(Unknown Source)
	... 21 more
]]></system-err>
  </testcase>
  <testcase name="testKeepFlowFileOrderingWithBatchMode" classname="org.apache.nifi.processors.standard.TestPutSQL" time="0.025"/>
  <testcase name="testStatementsFromProperty" classname="org.apache.nifi.processors.standard.TestPutSQL" time="0.03"/>
  <testcase name="testUsingTimestampValuesEpochAndString" classname="org.apache.nifi.processors.standard.TestPutSQL" time="0.015"/>
  <testcase name="testKeepFlowFileOrderingWithFragmentedTransaction" classname="org.apache.nifi.processors.standard.TestPutSQL" time="0.024"/>
  <testcase name="testProvenanceEventsWithFragmentedTransaction" classname="org.apache.nifi.processors.standard.TestPutSQL" time="0.022"/>
  <testcase name="testStatementsWithPreparedParameters" classname="org.apache.nifi.processors.standard.TestPutSQL" time="0.03"/>
  <testcase name="testFailInMiddleWithBadParameterValueRollbackOnFailure" classname="org.apache.nifi.processors.standard.TestPutSQL" time="0.019">
    <system-err><![CDATA[[pool-5309-thread-1] DEBUG org.apache.nifi.processors.standard.PutSQL - PutSQL[id=2c9e0f07-3fd9-43e1-9acc-72ea03e46c16] Adjusted TemporalFailure to Result{destination=ProcessException, penalty=Yield} based on context rollbackOnFailure=true, processedCount=0, transactional=true
[pool-5309-thread-1] ERROR org.apache.nifi.processors.standard.PutSQL - PutSQL[id=2c9e0f07-3fd9-43e1-9acc-72ea03e46c16] org.apache.nifi.processors.standard.PutSQL$$Lambda$2020/1547646810@78d2a405 failed to process due to org.apache.nifi.processor.exception.ProcessException: Failed to process 4 FlowFiles including FlowFile[0,90536919291808.mockFlowFile,54B] due to java.sql.BatchUpdateException: The check constraint 'SQL240502013516990' was violated while performing an INSERT or UPDATE on table '"APP"."PERSONS_AI"'.; rolling back session: org.apache.nifi.processor.exception.ProcessException: Failed to process 4 FlowFiles including FlowFile[0,90536919291808.mockFlowFile,54B] due to java.sql.BatchUpdateException: The check constraint 'SQL240502013516990' was violated while performing an INSERT or UPDATE on table '"APP"."PERSONS_AI"'.
org.apache.nifi.processor.exception.ProcessException: Failed to process 4 FlowFiles including FlowFile[0,90536919291808.mockFlowFile,54B] due to java.sql.BatchUpdateException: The check constraint 'SQL240502013516990' was violated while performing an INSERT or UPDATE on table '"APP"."PERSONS_AI"'.
	at org.apache.nifi.processor.util.pattern.ExceptionHandler.lambda$createOnGroupError$2(ExceptionHandler.java:226)
	at org.apache.nifi.processor.util.pattern.ExceptionHandler$OnError.lambda$andThen$0(ExceptionHandler.java:54)
	at org.apache.nifi.processors.standard.PutSQL.lambda$onBatchUpdateError$13(PutSQL.java:550)
	at org.apache.nifi.processor.util.pattern.ExceptionHandler$OnError.lambda$andThen$0(ExceptionHandler.java:54)
	at org.apache.nifi.processor.util.pattern.ExceptionHandler.execute(ExceptionHandler.java:148)
	at org.apache.nifi.processors.standard.PutSQL.lambda$new$10(PutSQL.java:401)
	at org.apache.nifi.processor.util.pattern.PutGroup.putFlowFiles(PutGroup.java:94)
	at org.apache.nifi.processor.util.pattern.Put.onTrigger(Put.java:103)
	at org.apache.nifi.processors.standard.PutSQL.lambda$onTrigger$19(PutSQL.java:635)
	at org.apache.nifi.processor.util.pattern.PartialFunctions.onTrigger(PartialFunctions.java:120)
	at org.apache.nifi.processor.util.pattern.RollbackOnFailure.onTrigger(RollbackOnFailure.java:184)
	at org.apache.nifi.processors.standard.PutSQL.onTrigger(PutSQL.java:635)
	at org.apache.nifi.util.StandardProcessorTestRunner$RunProcessor.call(StandardProcessorTestRunner.java:284)
	at org.apache.nifi.util.StandardProcessorTestRunner$RunProcessor.call(StandardProcessorTestRunner.java:278)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.sql.BatchUpdateException: The check constraint 'SQL240502013516990' was violated while performing an INSERT or UPDATE on table '"APP"."PERSONS_AI"'.
	at org.apache.derby.impl.jdbc.EmbedStatement.executeLargeBatch(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedStatement.executeBatch(Unknown Source)
	at org.apache.nifi.processors.standard.PutSQL.lambda$null$8(PutSQL.java:403)
	at org.apache.nifi.processor.util.pattern.ExceptionHandler.execute(ExceptionHandler.java:127)
	... 15 more
Caused by: org.apache.derby.shared.common.error.DerbySQLIntegrityConstraintViolationException: The check constraint 'SQL240502013516990' was violated while performing an INSERT or UPDATE on table '"APP"."PERSONS_AI"'.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeBatchElement(Unknown Source)
	... 19 more
Caused by: ERROR 23513: The check constraint 'SQL240502013516990' was violated while performing an INSERT or UPDATE on table '"APP"."PERSONS_AI"'.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.iapi.types.SQLBoolean.throwExceptionIfFalse(Unknown Source)
	at org.apache.derby.exe.ac73541f86x018fx36b7x5f61x00000eecc0200.e1(Unknown Source)
	at org.apache.derby.impl.services.reflect.DirectCall.invoke(Unknown Source)
	at org.apache.derby.impl.sql.execute.InsertResultSet.evaluateCheckConstraints(Unknown Source)
	at org.apache.derby.impl.sql.execute.InsertResultSet.normalInsertCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.InsertResultSet.open(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.executeStmt(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.execute(Unknown Source)
	... 21 more
[pool-5309-thread-1] WARN org.apache.nifi.processors.standard.PutSQL - PutSQL[id=2c9e0f07-3fd9-43e1-9acc-72ea03e46c16] Administratively yielding org.apache.nifi.processors.standard.PutSQL after rolling back due to org.apache.nifi.processor.exception.ProcessException: Failed to process 4 FlowFiles including FlowFile[0,90536919291808.mockFlowFile,54B] due to java.sql.BatchUpdateException: The check constraint 'SQL240502013516990' was violated while performing an INSERT or UPDATE on table '"APP"."PERSONS_AI"'.: org.apache.nifi.processor.exception.ProcessException: Failed to process 4 FlowFiles including FlowFile[0,90536919291808.mockFlowFile,54B] due to java.sql.BatchUpdateException: The check constraint 'SQL240502013516990' was violated while performing an INSERT or UPDATE on table '"APP"."PERSONS_AI"'.
[pool-5309-thread-1] WARN org.apache.nifi.processors.standard.PutSQL - 
org.apache.nifi.processor.exception.ProcessException: Failed to process 4 FlowFiles including FlowFile[0,90536919291808.mockFlowFile,54B] due to java.sql.BatchUpdateException: The check constraint 'SQL240502013516990' was violated while performing an INSERT or UPDATE on table '"APP"."PERSONS_AI"'.
	at org.apache.nifi.processor.util.pattern.ExceptionHandler.lambda$createOnGroupError$2(ExceptionHandler.java:226)
	at org.apache.nifi.processor.util.pattern.ExceptionHandler$OnError.lambda$andThen$0(ExceptionHandler.java:54)
	at org.apache.nifi.processors.standard.PutSQL.lambda$onBatchUpdateError$13(PutSQL.java:550)
	at org.apache.nifi.processor.util.pattern.ExceptionHandler$OnError.lambda$andThen$0(ExceptionHandler.java:54)
	at org.apache.nifi.processor.util.pattern.ExceptionHandler.execute(ExceptionHandler.java:148)
	at org.apache.nifi.processors.standard.PutSQL.lambda$new$10(PutSQL.java:401)
	at org.apache.nifi.processor.util.pattern.PutGroup.putFlowFiles(PutGroup.java:94)
	at org.apache.nifi.processor.util.pattern.Put.onTrigger(Put.java:103)
	at org.apache.nifi.processors.standard.PutSQL.lambda$onTrigger$19(PutSQL.java:635)
	at org.apache.nifi.processor.util.pattern.PartialFunctions.onTrigger(PartialFunctions.java:120)
	at org.apache.nifi.processor.util.pattern.RollbackOnFailure.onTrigger(RollbackOnFailure.java:184)
	at org.apache.nifi.processors.standard.PutSQL.onTrigger(PutSQL.java:635)
	at org.apache.nifi.util.StandardProcessorTestRunner$RunProcessor.call(StandardProcessorTestRunner.java:284)
	at org.apache.nifi.util.StandardProcessorTestRunner$RunProcessor.call(StandardProcessorTestRunner.java:278)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.sql.BatchUpdateException: The check constraint 'SQL240502013516990' was violated while performing an INSERT or UPDATE on table '"APP"."PERSONS_AI"'.
	at org.apache.derby.impl.jdbc.EmbedStatement.executeLargeBatch(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedStatement.executeBatch(Unknown Source)
	at org.apache.nifi.processors.standard.PutSQL.lambda$null$8(PutSQL.java:403)
	at org.apache.nifi.processor.util.pattern.ExceptionHandler.execute(ExceptionHandler.java:127)
	... 15 more
Caused by: org.apache.derby.shared.common.error.DerbySQLIntegrityConstraintViolationException: The check constraint 'SQL240502013516990' was violated while performing an INSERT or UPDATE on table '"APP"."PERSONS_AI"'.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeBatchElement(Unknown Source)
	... 19 more
Caused by: ERROR 23513: The check constraint 'SQL240502013516990' was violated while performing an INSERT or UPDATE on table '"APP"."PERSONS_AI"'.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.iapi.types.SQLBoolean.throwExceptionIfFalse(Unknown Source)
	at org.apache.derby.exe.ac73541f86x018fx36b7x5f61x00000eecc0200.e1(Unknown Source)
	at org.apache.derby.impl.services.reflect.DirectCall.invoke(Unknown Source)
	at org.apache.derby.impl.sql.execute.InsertResultSet.evaluateCheckConstraints(Unknown Source)
	at org.apache.derby.impl.sql.execute.InsertResultSet.normalInsertCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.InsertResultSet.open(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.executeStmt(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.execute(Unknown Source)
	... 21 more
]]></system-err>
  </testcase>
  <testcase name="testRetryableFailure" classname="org.apache.nifi.processors.standard.TestPutSQL" time="0.002">
    <system-err><![CDATA[[pool-5310-thread-1] ERROR org.apache.nifi.processors.standard.PutSQL - PutSQL[id=3ea433d5-2040-4eaa-b338-2da658b84730] Failed to update database for FlowFile[0,90536929402337.mockFlowFile,100B] due to java.sql.SQLException: Unit Test Generated SQLException; it is possible that retrying the operation will succeed, so routing to retry: java.sql.SQLException: Unit Test Generated SQLException
java.sql.SQLException: Unit Test Generated SQLException
	at org.apache.nifi.processors.standard.PutSQL$StatementFlowFileEnclosure.getCachedStatement(PutSQL.java:1014)
	at org.apache.nifi.processors.standard.PutSQL.lambda$null$4(PutSQL.java:343)
	at org.apache.nifi.processor.util.pattern.ExceptionHandler.execute(ExceptionHandler.java:127)
	at org.apache.nifi.processors.standard.PutSQL.lambda$new$5(PutSQL.java:342)
	at org.apache.nifi.processors.standard.PutSQL.lambda$new$7(PutSQL.java:387)
	at org.apache.nifi.processor.util.pattern.PutGroup.putFlowFiles(PutGroup.java:91)
	at org.apache.nifi.processor.util.pattern.Put.onTrigger(Put.java:103)
	at org.apache.nifi.processors.standard.PutSQL.lambda$onTrigger$19(PutSQL.java:635)
	at org.apache.nifi.processor.util.pattern.PartialFunctions.onTrigger(PartialFunctions.java:120)
	at org.apache.nifi.processor.util.pattern.RollbackOnFailure.onTrigger(RollbackOnFailure.java:184)
	at org.apache.nifi.processors.standard.PutSQL.onTrigger(PutSQL.java:635)
	at org.apache.nifi.util.StandardProcessorTestRunner$RunProcessor.call(StandardProcessorTestRunner.java:284)
	at org.apache.nifi.util.StandardProcessorTestRunner$RunProcessor.call(StandardProcessorTestRunner.java:278)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
[pool-5310-thread-1] ERROR org.apache.nifi.processors.standard.PutSQL - PutSQL[id=3ea433d5-2040-4eaa-b338-2da658b84730] Failed to update database for [] due to java.sql.SQLException: Unit Test Generated SQLException; it is possible that retrying the operation will succeed, so routing to retry: java.sql.SQLException: Unit Test Generated SQLException
java.sql.SQLException: Unit Test Generated SQLException
	at org.apache.nifi.processors.standard.PutSQL$StatementFlowFileEnclosure.getCachedStatement(PutSQL.java:1014)
	at org.apache.nifi.processors.standard.PutSQL.lambda$null$8(PutSQL.java:402)
	at org.apache.nifi.processor.util.pattern.ExceptionHandler.execute(ExceptionHandler.java:127)
	at org.apache.nifi.processors.standard.PutSQL.lambda$new$10(PutSQL.java:401)
	at org.apache.nifi.processor.util.pattern.PutGroup.putFlowFiles(PutGroup.java:94)
	at org.apache.nifi.processor.util.pattern.Put.onTrigger(Put.java:103)
	at org.apache.nifi.processors.standard.PutSQL.lambda$onTrigger$19(PutSQL.java:635)
	at org.apache.nifi.processor.util.pattern.PartialFunctions.onTrigger(PartialFunctions.java:120)
	at org.apache.nifi.processor.util.pattern.RollbackOnFailure.onTrigger(RollbackOnFailure.java:184)
	at org.apache.nifi.processors.standard.PutSQL.onTrigger(PutSQL.java:635)
	at org.apache.nifi.util.StandardProcessorTestRunner$RunProcessor.call(StandardProcessorTestRunner.java:284)
	at org.apache.nifi.util.StandardProcessorTestRunner$RunProcessor.call(StandardProcessorTestRunner.java:278)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
]]></system-err>
  </testcase>
  <testcase name="testFailInMiddleWithBadParameterValueAndNotSupportTransaction" classname="org.apache.nifi.processors.standard.TestPutSQL" time="0.021">
    <system-err><![CDATA[[pool-5311-thread-1] ERROR org.apache.nifi.processors.standard.PutSQL - PutSQL[id=d34a0639-50c1-471d-a265-80f450435765] Failed to update database due to a failed batch update, java.sql.BatchUpdateException: The check constraint 'SQL240502013517020' was violated while performing an INSERT or UPDATE on table '"APP"."PERSONS_AI"'.. There were a total of 1 FlowFiles that failed, 1 that succeeded, and 2 that were not execute and will be routed to retry; : java.sql.BatchUpdateException: The check constraint 'SQL240502013517020' was violated while performing an INSERT or UPDATE on table '"APP"."PERSONS_AI"'.
java.sql.BatchUpdateException: The check constraint 'SQL240502013517020' was violated while performing an INSERT or UPDATE on table '"APP"."PERSONS_AI"'.
	at org.apache.derby.impl.jdbc.EmbedStatement.executeLargeBatch(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedStatement.executeBatch(Unknown Source)
	at org.apache.nifi.processors.standard.PutSQL.lambda$null$8(PutSQL.java:403)
	at org.apache.nifi.processor.util.pattern.ExceptionHandler.execute(ExceptionHandler.java:127)
	at org.apache.nifi.processors.standard.PutSQL.lambda$new$10(PutSQL.java:401)
	at org.apache.nifi.processor.util.pattern.PutGroup.putFlowFiles(PutGroup.java:94)
	at org.apache.nifi.processor.util.pattern.Put.onTrigger(Put.java:103)
	at org.apache.nifi.processors.standard.PutSQL.lambda$onTrigger$19(PutSQL.java:635)
	at org.apache.nifi.processor.util.pattern.PartialFunctions.onTrigger(PartialFunctions.java:120)
	at org.apache.nifi.processor.util.pattern.RollbackOnFailure.onTrigger(RollbackOnFailure.java:184)
	at org.apache.nifi.processors.standard.PutSQL.onTrigger(PutSQL.java:635)
	at org.apache.nifi.util.StandardProcessorTestRunner$RunProcessor.call(StandardProcessorTestRunner.java:284)
	at org.apache.nifi.util.StandardProcessorTestRunner$RunProcessor.call(StandardProcessorTestRunner.java:278)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: org.apache.derby.shared.common.error.DerbySQLIntegrityConstraintViolationException: The check constraint 'SQL240502013517020' was violated while performing an INSERT or UPDATE on table '"APP"."PERSONS_AI"'.
	at org.apache.derby.impl.jdbc.SQLExceptionFactory.getSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
	at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedStatement.executeStatement(Unknown Source)
	at org.apache.derby.impl.jdbc.EmbedPreparedStatement.executeBatchElement(Unknown Source)
	... 19 more
Caused by: ERROR 23513: The check constraint 'SQL240502013517020' was violated while performing an INSERT or UPDATE on table '"APP"."PERSONS_AI"'.
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.iapi.error.StandardException.newException(Unknown Source)
	at org.apache.derby.iapi.types.SQLBoolean.throwExceptionIfFalse(Unknown Source)
	at org.apache.derby.exe.acb1f69f92x018fx36b7x5f61x00000eecc0200.e1(Unknown Source)
	at org.apache.derby.impl.services.reflect.DirectCall.invoke(Unknown Source)
	at org.apache.derby.impl.sql.execute.InsertResultSet.evaluateCheckConstraints(Unknown Source)
	at org.apache.derby.impl.sql.execute.InsertResultSet.normalInsertCore(Unknown Source)
	at org.apache.derby.impl.sql.execute.InsertResultSet.open(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.executeStmt(Unknown Source)
	at org.apache.derby.impl.sql.GenericPreparedStatement.execute(Unknown Source)
	... 21 more
]]></system-err>
  </testcase>
</testsuite>